# メインルーターの設定
name = "tools-router"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# カスタムドメイン設定
routes = [
  { pattern = "tools.elchika.app", custom_domain = true }
]

# 注意: 子アプリはCloudflare Pagesとして独立してデプロイされます
# リバースプロキシとしてPagesデプロイメントにルーティングします
