export interface Emoji {
  emoji: string;
  name: string;
  keywords: string[];
  category: EmojiCategory;
}

export type EmojiCategory =
  | 'Smileys'
  | 'People'
  | 'Animals'
  | 'Food'
  | 'Travel'
  | 'Activities'
  | 'Objects'
  | 'Symbols'
  | 'Flags';

export const CATEGORIES: EmojiCategory[] = [
  'Smileys',
  'People',
  'Animals',
  'Food',
  'Travel',
  'Activities',
  'Objects',
  'Symbols',
  'Flags',
];

export const EMOJI_DATABASE: Emoji[] = [
  // Smileys (~60)
  { emoji: '\u{1F600}', name: 'grinning face', keywords: ['happy', 'smile', 'joy'], category: 'Smileys' },
  { emoji: '\u{1F601}', name: 'beaming face', keywords: ['happy', 'smile', 'grin'], category: 'Smileys' },
  { emoji: '\u{1F602}', name: 'face with tears of joy', keywords: ['laugh', 'cry', 'funny'], category: 'Smileys' },
  { emoji: '\u{1F603}', name: 'smiling face open mouth', keywords: ['happy', 'smile'], category: 'Smileys' },
  { emoji: '\u{1F604}', name: 'smiling face with eyes', keywords: ['happy', 'joy'], category: 'Smileys' },
  { emoji: '\u{1F605}', name: 'grinning with sweat', keywords: ['nervous', 'smile'], category: 'Smileys' },
  { emoji: '\u{1F606}', name: 'squinting face', keywords: ['laugh', 'happy'], category: 'Smileys' },
  { emoji: '\u{1F609}', name: 'winking face', keywords: ['wink', 'flirt'], category: 'Smileys' },
  { emoji: '\u{1F60A}', name: 'smiling with blush', keywords: ['happy', 'blush', 'shy'], category: 'Smileys' },
  { emoji: '\u{1F60B}', name: 'face savoring food', keywords: ['yummy', 'delicious'], category: 'Smileys' },
  { emoji: '\u{1F60E}', name: 'smiling with sunglasses', keywords: ['cool', 'sunglasses'], category: 'Smileys' },
  { emoji: '\u{1F60D}', name: 'heart eyes', keywords: ['love', 'crush', 'adore'], category: 'Smileys' },
  { emoji: '\u{1F618}', name: 'face blowing kiss', keywords: ['kiss', 'love', 'flirt'], category: 'Smileys' },
  { emoji: '\u{1F617}', name: 'kissing face', keywords: ['kiss', 'love'], category: 'Smileys' },
  { emoji: '\u{1F619}', name: 'kissing with eyes', keywords: ['kiss', 'love'], category: 'Smileys' },
  { emoji: '\u{1F61A}', name: 'kissing with blush', keywords: ['kiss', 'blush'], category: 'Smileys' },
  { emoji: '\u{1F642}', name: 'slightly smiling', keywords: ['smile', 'subtle'], category: 'Smileys' },
  { emoji: '\u{1F917}', name: 'hugging face', keywords: ['hug', 'warm'], category: 'Smileys' },
  { emoji: '\u{1F914}', name: 'thinking face', keywords: ['think', 'hmm', 'ponder'], category: 'Smileys' },
  { emoji: '\u{1F610}', name: 'neutral face', keywords: ['meh', 'blank', 'neutral'], category: 'Smileys' },
  { emoji: '\u{1F611}', name: 'expressionless', keywords: ['blank', 'meh'], category: 'Smileys' },
  { emoji: '\u{1F636}', name: 'face without mouth', keywords: ['silent', 'mute'], category: 'Smileys' },
  { emoji: '\u{1F644}', name: 'face with rolling eyes', keywords: ['eyeroll', 'annoyed'], category: 'Smileys' },
  { emoji: '\u{1F60F}', name: 'smirking face', keywords: ['smirk', 'sly'], category: 'Smileys' },
  { emoji: '\u{1F623}', name: 'persevering face', keywords: ['struggle', 'pain'], category: 'Smileys' },
  { emoji: '\u{1F625}', name: 'sad but relieved', keywords: ['sad', 'relief'], category: 'Smileys' },
  { emoji: '\u{1F62E}', name: 'face with open mouth', keywords: ['surprise', 'wow'], category: 'Smileys' },
  { emoji: '\u{1F910}', name: 'zipper mouth', keywords: ['quiet', 'secret', 'shh'], category: 'Smileys' },
  { emoji: '\u{1F922}', name: 'nauseated face', keywords: ['sick', 'nausea'], category: 'Smileys' },
  { emoji: '\u{1F927}', name: 'sneezing face', keywords: ['sick', 'cold', 'sneeze'], category: 'Smileys' },
  { emoji: '\u{1F637}', name: 'face with mask', keywords: ['sick', 'mask'], category: 'Smileys' },
  { emoji: '\u{1F912}', name: 'face with thermometer', keywords: ['sick', 'fever'], category: 'Smileys' },
  { emoji: '\u{1F915}', name: 'face with bandage', keywords: ['hurt', 'injury'], category: 'Smileys' },
  { emoji: '\u{1F608}', name: 'smiling devil', keywords: ['devil', 'evil', 'horns'], category: 'Smileys' },
  { emoji: '\u{1F47F}', name: 'angry devil', keywords: ['devil', 'angry'], category: 'Smileys' },
  { emoji: '\u{1F480}', name: 'skull', keywords: ['death', 'dead', 'skeleton'], category: 'Smileys' },
  { emoji: '\u{1F47B}', name: 'ghost', keywords: ['ghost', 'halloween', 'spooky'], category: 'Smileys' },
  { emoji: '\u{1F47D}', name: 'alien', keywords: ['alien', 'ufo', 'space'], category: 'Smileys' },
  { emoji: '\u{1F916}', name: 'robot', keywords: ['robot', 'machine', 'ai'], category: 'Smileys' },
  { emoji: '\u{1F4A9}', name: 'pile of poo', keywords: ['poo', 'poop'], category: 'Smileys' },
  { emoji: '\u{1F621}', name: 'pouting face', keywords: ['angry', 'rage', 'mad'], category: 'Smileys' },
  { emoji: '\u{1F620}', name: 'angry face', keywords: ['angry', 'mad'], category: 'Smileys' },
  { emoji: '\u{1F62D}', name: 'loudly crying', keywords: ['cry', 'sad', 'sob'], category: 'Smileys' },
  { emoji: '\u{1F622}', name: 'crying face', keywords: ['cry', 'sad', 'tear'], category: 'Smileys' },
  { emoji: '\u{1F62A}', name: 'sleepy face', keywords: ['tired', 'sleep'], category: 'Smileys' },
  { emoji: '\u{1F634}', name: 'sleeping face', keywords: ['sleep', 'zzz'], category: 'Smileys' },
  { emoji: '\u{1F632}', name: 'astonished face', keywords: ['shocked', 'surprise'], category: 'Smileys' },
  { emoji: '\u{1F631}', name: 'face screaming', keywords: ['scream', 'fear', 'horror'], category: 'Smileys' },
  { emoji: '\u{1F633}', name: 'flushed face', keywords: ['embarrassed', 'blush'], category: 'Smileys' },
  { emoji: '\u{1F61C}', name: 'winking tongue', keywords: ['silly', 'playful', 'tongue'], category: 'Smileys' },
  { emoji: '\u{1F61D}', name: 'squinting tongue', keywords: ['silly', 'tongue'], category: 'Smileys' },
  { emoji: '\u{1F61B}', name: 'face with tongue', keywords: ['tongue', 'playful'], category: 'Smileys' },
  { emoji: '\u{1F911}', name: 'money mouth', keywords: ['money', 'rich', 'dollar'], category: 'Smileys' },
  { emoji: '\u{1F913}', name: 'nerd face', keywords: ['nerd', 'geek', 'glasses'], category: 'Smileys' },
  { emoji: '\u{1F924}', name: 'drooling face', keywords: ['drool', 'hungry'], category: 'Smileys' },
  { emoji: '\u{1F62C}', name: 'grimacing face', keywords: ['awkward', 'grimace'], category: 'Smileys' },

  // People (~55)
  { emoji: '\u{1F44D}', name: 'thumbs up', keywords: ['like', 'approve', 'good', 'yes'], category: 'People' },
  { emoji: '\u{1F44E}', name: 'thumbs down', keywords: ['dislike', 'bad', 'no'], category: 'People' },
  { emoji: '\u{1F44F}', name: 'clapping hands', keywords: ['clap', 'bravo', 'applause'], category: 'People' },
  { emoji: '\u{1F64C}', name: 'raising hands', keywords: ['celebrate', 'hooray', 'praise'], category: 'People' },
  { emoji: '\u{1F44B}', name: 'waving hand', keywords: ['wave', 'hello', 'bye', 'hi'], category: 'People' },
  { emoji: '\u{270B}', name: 'raised hand', keywords: ['stop', 'high five'], category: 'People' },
  { emoji: '\u{1F44C}', name: 'ok hand', keywords: ['ok', 'perfect', 'fine'], category: 'People' },
  { emoji: '\u{270C}\u{FE0F}', name: 'victory hand', keywords: ['peace', 'victory', 'v'], category: 'People' },
  { emoji: '\u{1F91E}', name: 'crossed fingers', keywords: ['luck', 'hope'], category: 'People' },
  { emoji: '\u{1F919}', name: 'call me hand', keywords: ['call', 'shaka'], category: 'People' },
  { emoji: '\u{1F4AA}', name: 'flexed biceps', keywords: ['strong', 'muscle', 'power'], category: 'People' },
  { emoji: '\u{1F64F}', name: 'folded hands', keywords: ['pray', 'please', 'thanks'], category: 'People' },
  { emoji: '\u{1F91D}', name: 'handshake', keywords: ['deal', 'agree', 'meet'], category: 'People' },
  { emoji: '\u{261D}\u{FE0F}', name: 'index pointing up', keywords: ['point', 'one', 'up'], category: 'People' },
  { emoji: '\u{1F448}', name: 'pointing left', keywords: ['left', 'point'], category: 'People' },
  { emoji: '\u{1F449}', name: 'pointing right', keywords: ['right', 'point'], category: 'People' },
  { emoji: '\u{1F446}', name: 'pointing up', keywords: ['up', 'point'], category: 'People' },
  { emoji: '\u{1F447}', name: 'pointing down', keywords: ['down', 'point'], category: 'People' },
  { emoji: '\u{270D}\u{FE0F}', name: 'writing hand', keywords: ['write', 'pen'], category: 'People' },
  { emoji: '\u{1F918}', name: 'sign of horns', keywords: ['rock', 'metal'], category: 'People' },
  { emoji: '\u{1F590}\u{FE0F}', name: 'hand with fingers', keywords: ['hand', 'five'], category: 'People' },
  { emoji: '\u{1F466}', name: 'boy', keywords: ['boy', 'child', 'kid'], category: 'People' },
  { emoji: '\u{1F467}', name: 'girl', keywords: ['girl', 'child', 'kid'], category: 'People' },
  { emoji: '\u{1F468}', name: 'man', keywords: ['man', 'male', 'adult'], category: 'People' },
  { emoji: '\u{1F469}', name: 'woman', keywords: ['woman', 'female', 'adult'], category: 'People' },
  { emoji: '\u{1F474}', name: 'old man', keywords: ['elderly', 'grandfather'], category: 'People' },
  { emoji: '\u{1F475}', name: 'old woman', keywords: ['elderly', 'grandmother'], category: 'People' },
  { emoji: '\u{1F476}', name: 'baby', keywords: ['baby', 'infant', 'newborn'], category: 'People' },
  { emoji: '\u{1F471}', name: 'person blond hair', keywords: ['blond', 'person'], category: 'People' },
  { emoji: '\u{1F46B}', name: 'couple', keywords: ['couple', 'love', 'date'], category: 'People' },
  { emoji: '\u{1F46A}', name: 'family', keywords: ['family', 'parents', 'children'], category: 'People' },
  { emoji: '\u{1F46C}', name: 'two men', keywords: ['men', 'friends'], category: 'People' },
  { emoji: '\u{1F46D}', name: 'two women', keywords: ['women', 'friends'], category: 'People' },
  { emoji: '\u{1F647}', name: 'person bowing', keywords: ['bow', 'sorry', 'respect'], category: 'People' },
  { emoji: '\u{1F481}', name: 'person tipping hand', keywords: ['help', 'information'], category: 'People' },
  { emoji: '\u{1F645}', name: 'person gesturing no', keywords: ['no', 'stop', 'forbidden'], category: 'People' },
  { emoji: '\u{1F646}', name: 'person gesturing ok', keywords: ['ok', 'yes', 'approve'], category: 'People' },
  { emoji: '\u{1F64B}', name: 'person raising hand', keywords: ['raise', 'question', 'volunteer'], category: 'People' },
  { emoji: '\u{1F926}', name: 'person facepalming', keywords: ['facepalm', 'disbelief'], category: 'People' },
  { emoji: '\u{1F937}', name: 'person shrugging', keywords: ['shrug', 'dunno', 'idk'], category: 'People' },
  { emoji: '\u{1F483}', name: 'woman dancing', keywords: ['dance', 'party'], category: 'People' },
  { emoji: '\u{1F57A}', name: 'man dancing', keywords: ['dance', 'party'], category: 'People' },
  { emoji: '\u{1F440}', name: 'eyes', keywords: ['eyes', 'look', 'see', 'watch'], category: 'People' },
  { emoji: '\u{1F441}\u{FE0F}', name: 'eye', keywords: ['eye', 'see'], category: 'People' },
  { emoji: '\u{1F443}', name: 'nose', keywords: ['nose', 'smell'], category: 'People' },
  { emoji: '\u{1F442}', name: 'ear', keywords: ['ear', 'hear', 'listen'], category: 'People' },
  { emoji: '\u{1F444}', name: 'mouth', keywords: ['mouth', 'lips', 'kiss'], category: 'People' },
  { emoji: '\u{1F445}', name: 'tongue', keywords: ['tongue', 'taste'], category: 'People' },

  // Animals (~55)
  { emoji: '\u{1F436}', name: 'dog face', keywords: ['dog', 'puppy', 'pet'], category: 'Animals' },
  { emoji: '\u{1F431}', name: 'cat face', keywords: ['cat', 'kitten', 'pet'], category: 'Animals' },
  { emoji: '\u{1F42D}', name: 'mouse face', keywords: ['mouse', 'rodent'], category: 'Animals' },
  { emoji: '\u{1F439}', name: 'hamster face', keywords: ['hamster', 'pet'], category: 'Animals' },
  { emoji: '\u{1F430}', name: 'rabbit face', keywords: ['rabbit', 'bunny'], category: 'Animals' },
  { emoji: '\u{1F43B}', name: 'bear face', keywords: ['bear', 'animal'], category: 'Animals' },
  { emoji: '\u{1F43C}', name: 'panda face', keywords: ['panda', 'bear'], category: 'Animals' },
  { emoji: '\u{1F428}', name: 'koala', keywords: ['koala', 'australia'], category: 'Animals' },
  { emoji: '\u{1F42F}', name: 'tiger face', keywords: ['tiger', 'cat'], category: 'Animals' },
  { emoji: '\u{1F981}', name: 'lion face', keywords: ['lion', 'king'], category: 'Animals' },
  { emoji: '\u{1F42E}', name: 'cow face', keywords: ['cow', 'farm'], category: 'Animals' },
  { emoji: '\u{1F437}', name: 'pig face', keywords: ['pig', 'farm'], category: 'Animals' },
  { emoji: '\u{1F438}', name: 'frog face', keywords: ['frog', 'toad'], category: 'Animals' },
  { emoji: '\u{1F435}', name: 'monkey face', keywords: ['monkey', 'ape'], category: 'Animals' },
  { emoji: '\u{1F414}', name: 'chicken', keywords: ['chicken', 'hen', 'farm'], category: 'Animals' },
  { emoji: '\u{1F427}', name: 'penguin', keywords: ['penguin', 'arctic'], category: 'Animals' },
  { emoji: '\u{1F426}', name: 'bird', keywords: ['bird', 'fly'], category: 'Animals' },
  { emoji: '\u{1F424}', name: 'baby chick', keywords: ['chick', 'baby', 'bird'], category: 'Animals' },
  { emoji: '\u{1F40D}', name: 'snake', keywords: ['snake', 'reptile'], category: 'Animals' },
  { emoji: '\u{1F422}', name: 'turtle', keywords: ['turtle', 'tortoise', 'slow'], category: 'Animals' },
  { emoji: '\u{1F41B}', name: 'bug', keywords: ['bug', 'insect'], category: 'Animals' },
  { emoji: '\u{1F41D}', name: 'honeybee', keywords: ['bee', 'honey'], category: 'Animals' },
  { emoji: '\u{1F41C}', name: 'ant', keywords: ['ant', 'insect'], category: 'Animals' },
  { emoji: '\u{1F41E}', name: 'ladybug', keywords: ['ladybug', 'insect'], category: 'Animals' },
  { emoji: '\u{1F40C}', name: 'snail', keywords: ['snail', 'slow'], category: 'Animals' },
  { emoji: '\u{1F419}', name: 'octopus', keywords: ['octopus', 'sea'], category: 'Animals' },
  { emoji: '\u{1F420}', name: 'tropical fish', keywords: ['fish', 'tropical'], category: 'Animals' },
  { emoji: '\u{1F41F}', name: 'fish', keywords: ['fish', 'sea'], category: 'Animals' },
  { emoji: '\u{1F421}', name: 'blowfish', keywords: ['blowfish', 'puffer'], category: 'Animals' },
  { emoji: '\u{1F42C}', name: 'dolphin', keywords: ['dolphin', 'sea'], category: 'Animals' },
  { emoji: '\u{1F433}', name: 'whale', keywords: ['whale', 'ocean'], category: 'Animals' },
  { emoji: '\u{1F40B}', name: 'whale', keywords: ['whale', 'ocean', 'big'], category: 'Animals' },
  { emoji: '\u{1F40A}', name: 'crocodile', keywords: ['crocodile', 'alligator'], category: 'Animals' },
  { emoji: '\u{1F406}', name: 'leopard', keywords: ['leopard', 'cat'], category: 'Animals' },
  { emoji: '\u{1F405}', name: 'tiger', keywords: ['tiger', 'cat'], category: 'Animals' },
  { emoji: '\u{1F403}', name: 'water buffalo', keywords: ['buffalo', 'animal'], category: 'Animals' },
  { emoji: '\u{1F402}', name: 'ox', keywords: ['ox', 'cow'], category: 'Animals' },
  { emoji: '\u{1F404}', name: 'cow', keywords: ['cow', 'farm'], category: 'Animals' },
  { emoji: '\u{1F40E}', name: 'horse', keywords: ['horse', 'racing'], category: 'Animals' },
  { emoji: '\u{1F434}', name: 'horse face', keywords: ['horse', 'pony'], category: 'Animals' },
  { emoji: '\u{1F411}', name: 'sheep', keywords: ['sheep', 'lamb'], category: 'Animals' },
  { emoji: '\u{1F410}', name: 'goat', keywords: ['goat', 'farm'], category: 'Animals' },
  { emoji: '\u{1F418}', name: 'elephant', keywords: ['elephant', 'big'], category: 'Animals' },
  { emoji: '\u{1F98A}', name: 'fox', keywords: ['fox', 'clever'], category: 'Animals' },
  { emoji: '\u{1F43A}', name: 'wolf', keywords: ['wolf', 'howl'], category: 'Animals' },
  { emoji: '\u{1F415}', name: 'dog', keywords: ['dog', 'pet'], category: 'Animals' },
  { emoji: '\u{1F429}', name: 'poodle', keywords: ['poodle', 'dog'], category: 'Animals' },
  { emoji: '\u{1F408}', name: 'cat', keywords: ['cat', 'pet'], category: 'Animals' },
  { emoji: '\u{1F98B}', name: 'butterfly', keywords: ['butterfly', 'insect', 'beautiful'], category: 'Animals' },
  { emoji: '\u{1F40F}', name: 'ram', keywords: ['ram', 'sheep'], category: 'Animals' },
  { emoji: '\u{1F417}', name: 'boar', keywords: ['boar', 'pig', 'wild'], category: 'Animals' },
  { emoji: '\u{1F412}', name: 'monkey', keywords: ['monkey', 'ape', 'primate'], category: 'Animals' },
  { emoji: '\u{1F413}', name: 'rooster', keywords: ['rooster', 'chicken', 'cock'], category: 'Animals' },
  { emoji: '\u{1F423}', name: 'hatching chick', keywords: ['chick', 'egg', 'bird'], category: 'Animals' },

  // Food (~55)
  { emoji: '\u{1F34E}', name: 'red apple', keywords: ['apple', 'fruit'], category: 'Food' },
  { emoji: '\u{1F34A}', name: 'tangerine', keywords: ['orange', 'citrus', 'fruit'], category: 'Food' },
  { emoji: '\u{1F34B}', name: 'lemon', keywords: ['lemon', 'citrus', 'sour'], category: 'Food' },
  { emoji: '\u{1F34C}', name: 'banana', keywords: ['banana', 'fruit'], category: 'Food' },
  { emoji: '\u{1F34D}', name: 'pineapple', keywords: ['pineapple', 'fruit'], category: 'Food' },
  { emoji: '\u{1F347}', name: 'grapes', keywords: ['grapes', 'wine', 'fruit'], category: 'Food' },
  { emoji: '\u{1F348}', name: 'melon', keywords: ['melon', 'fruit'], category: 'Food' },
  { emoji: '\u{1F349}', name: 'watermelon', keywords: ['watermelon', 'summer'], category: 'Food' },
  { emoji: '\u{1F34F}', name: 'green apple', keywords: ['apple', 'fruit', 'green'], category: 'Food' },
  { emoji: '\u{1F351}', name: 'peach', keywords: ['peach', 'fruit'], category: 'Food' },
  { emoji: '\u{1F352}', name: 'cherries', keywords: ['cherry', 'fruit'], category: 'Food' },
  { emoji: '\u{1F353}', name: 'strawberry', keywords: ['strawberry', 'fruit', 'berry'], category: 'Food' },
  { emoji: '\u{1F345}', name: 'tomato', keywords: ['tomato', 'vegetable'], category: 'Food' },
  { emoji: '\u{1F346}', name: 'eggplant', keywords: ['eggplant', 'aubergine'], category: 'Food' },
  { emoji: '\u{1F33D}', name: 'corn', keywords: ['corn', 'maize'], category: 'Food' },
  { emoji: '\u{1F336}\u{FE0F}', name: 'hot pepper', keywords: ['pepper', 'spicy', 'chili'], category: 'Food' },
  { emoji: '\u{1F344}', name: 'mushroom', keywords: ['mushroom', 'fungus'], category: 'Food' },
  { emoji: '\u{1F955}', name: 'carrot', keywords: ['carrot', 'vegetable'], category: 'Food' },
  { emoji: '\u{1F354}', name: 'hamburger', keywords: ['burger', 'fast food', 'meat'], category: 'Food' },
  { emoji: '\u{1F355}', name: 'pizza', keywords: ['pizza', 'food'], category: 'Food' },
  { emoji: '\u{1F35E}', name: 'bread', keywords: ['bread', 'bakery'], category: 'Food' },
  { emoji: '\u{1F357}', name: 'poultry leg', keywords: ['chicken', 'meat', 'drumstick'], category: 'Food' },
  { emoji: '\u{1F356}', name: 'meat on bone', keywords: ['meat', 'bone'], category: 'Food' },
  { emoji: '\u{1F35D}', name: 'spaghetti', keywords: ['pasta', 'noodle', 'italian'], category: 'Food' },
  { emoji: '\u{1F35C}', name: 'steaming bowl', keywords: ['ramen', 'noodle', 'soup'], category: 'Food' },
  { emoji: '\u{1F363}', name: 'sushi', keywords: ['sushi', 'japanese', 'fish'], category: 'Food' },
  { emoji: '\u{1F364}', name: 'fried shrimp', keywords: ['shrimp', 'tempura'], category: 'Food' },
  { emoji: '\u{1F359}', name: 'rice ball', keywords: ['rice', 'onigiri', 'japanese'], category: 'Food' },
  { emoji: '\u{1F35A}', name: 'cooked rice', keywords: ['rice', 'bowl'], category: 'Food' },
  { emoji: '\u{1F35B}', name: 'curry rice', keywords: ['curry', 'rice'], category: 'Food' },
  { emoji: '\u{1F35F}', name: 'french fries', keywords: ['fries', 'fast food', 'potato'], category: 'Food' },
  { emoji: '\u{1F369}', name: 'doughnut', keywords: ['donut', 'sweet', 'dessert'], category: 'Food' },
  { emoji: '\u{1F36A}', name: 'cookie', keywords: ['cookie', 'sweet'], category: 'Food' },
  { emoji: '\u{1F370}', name: 'shortcake', keywords: ['cake', 'dessert', 'sweet'], category: 'Food' },
  { emoji: '\u{1F382}', name: 'birthday cake', keywords: ['birthday', 'cake', 'celebration'], category: 'Food' },
  { emoji: '\u{1F366}', name: 'soft ice cream', keywords: ['ice cream', 'dessert'], category: 'Food' },
  { emoji: '\u{1F367}', name: 'shaved ice', keywords: ['ice', 'dessert', 'summer'], category: 'Food' },
  { emoji: '\u{1F36B}', name: 'chocolate bar', keywords: ['chocolate', 'sweet'], category: 'Food' },
  { emoji: '\u{1F36C}', name: 'candy', keywords: ['candy', 'sweet'], category: 'Food' },
  { emoji: '\u{1F36D}', name: 'lollipop', keywords: ['lollipop', 'candy', 'sweet'], category: 'Food' },
  { emoji: '\u{2615}', name: 'hot beverage', keywords: ['coffee', 'tea', 'hot', 'drink'], category: 'Food' },
  { emoji: '\u{1F375}', name: 'teacup', keywords: ['tea', 'green tea', 'japanese'], category: 'Food' },
  { emoji: '\u{1F376}', name: 'sake', keywords: ['sake', 'japanese', 'alcohol'], category: 'Food' },
  { emoji: '\u{1F37A}', name: 'beer mug', keywords: ['beer', 'alcohol', 'drink'], category: 'Food' },
  { emoji: '\u{1F37B}', name: 'clinking beer', keywords: ['beer', 'cheers', 'celebrate'], category: 'Food' },
  { emoji: '\u{1F377}', name: 'wine glass', keywords: ['wine', 'alcohol', 'drink'], category: 'Food' },
  { emoji: '\u{1F378}', name: 'cocktail glass', keywords: ['cocktail', 'drink', 'martini'], category: 'Food' },
  { emoji: '\u{1F379}', name: 'tropical drink', keywords: ['cocktail', 'tropical'], category: 'Food' },
  { emoji: '\u{1F37E}', name: 'bottle with cork', keywords: ['champagne', 'celebration'], category: 'Food' },
  { emoji: '\u{1F374}', name: 'fork and knife', keywords: ['food', 'eat', 'dining'], category: 'Food' },

  // Travel (~55)
  { emoji: '\u{1F697}', name: 'automobile', keywords: ['car', 'drive', 'vehicle'], category: 'Travel' },
  { emoji: '\u{1F695}', name: 'taxi', keywords: ['taxi', 'cab'], category: 'Travel' },
  { emoji: '\u{1F68C}', name: 'bus', keywords: ['bus', 'public transport'], category: 'Travel' },
  { emoji: '\u{1F691}', name: 'ambulance', keywords: ['ambulance', 'emergency'], category: 'Travel' },
  { emoji: '\u{1F692}', name: 'fire engine', keywords: ['fire', 'emergency', 'truck'], category: 'Travel' },
  { emoji: '\u{1F693}', name: 'police car', keywords: ['police', 'emergency'], category: 'Travel' },
  { emoji: '\u{1F699}', name: 'sport utility', keywords: ['suv', 'car', 'vehicle'], category: 'Travel' },
  { emoji: '\u{1F69A}', name: 'delivery truck', keywords: ['truck', 'delivery'], category: 'Travel' },
  { emoji: '\u{1F6B2}', name: 'bicycle', keywords: ['bike', 'bicycle', 'cycling'], category: 'Travel' },
  { emoji: '\u{1F6B6}', name: 'person walking', keywords: ['walk', 'pedestrian'], category: 'Travel' },
  { emoji: '\u{2708}\u{FE0F}', name: 'airplane', keywords: ['plane', 'fly', 'travel'], category: 'Travel' },
  { emoji: '\u{1F680}', name: 'rocket', keywords: ['rocket', 'space', 'launch'], category: 'Travel' },
  { emoji: '\u{1F681}', name: 'helicopter', keywords: ['helicopter', 'fly'], category: 'Travel' },
  { emoji: '\u{1F682}', name: 'locomotive', keywords: ['train', 'railway'], category: 'Travel' },
  { emoji: '\u{1F684}', name: 'high-speed train', keywords: ['train', 'shinkansen', 'fast'], category: 'Travel' },
  { emoji: '\u{1F685}', name: 'bullet train', keywords: ['train', 'shinkansen'], category: 'Travel' },
  { emoji: '\u{1F6A2}', name: 'ship', keywords: ['ship', 'boat', 'cruise'], category: 'Travel' },
  { emoji: '\u{26F5}', name: 'sailboat', keywords: ['boat', 'sail'], category: 'Travel' },
  { emoji: '\u{1F3E0}', name: 'house', keywords: ['house', 'home'], category: 'Travel' },
  { emoji: '\u{1F3E2}', name: 'office building', keywords: ['office', 'work', 'building'], category: 'Travel' },
  { emoji: '\u{1F3E5}', name: 'hospital', keywords: ['hospital', 'medical'], category: 'Travel' },
  { emoji: '\u{1F3EB}', name: 'school', keywords: ['school', 'education'], category: 'Travel' },
  { emoji: '\u{1F3EA}', name: 'convenience store', keywords: ['store', 'shop'], category: 'Travel' },
  { emoji: '\u{26F2}', name: 'fountain', keywords: ['fountain', 'park'], category: 'Travel' },
  { emoji: '\u{26FA}', name: 'tent', keywords: ['tent', 'camping', 'outdoor'], category: 'Travel' },
  { emoji: '\u{1F30D}', name: 'globe europe', keywords: ['earth', 'world', 'globe'], category: 'Travel' },
  { emoji: '\u{1F30E}', name: 'globe americas', keywords: ['earth', 'world', 'globe'], category: 'Travel' },
  { emoji: '\u{1F30F}', name: 'globe asia', keywords: ['earth', 'world', 'globe', 'japan'], category: 'Travel' },
  { emoji: '\u{1F301}', name: 'foggy', keywords: ['fog', 'weather'], category: 'Travel' },
  { emoji: '\u{1F303}', name: 'night with stars', keywords: ['night', 'city', 'stars'], category: 'Travel' },
  { emoji: '\u{1F304}', name: 'sunrise mountains', keywords: ['sunrise', 'morning'], category: 'Travel' },
  { emoji: '\u{1F305}', name: 'sunrise', keywords: ['sunrise', 'morning', 'sun'], category: 'Travel' },
  { emoji: '\u{1F307}', name: 'sunset', keywords: ['sunset', 'evening'], category: 'Travel' },
  { emoji: '\u{1F308}', name: 'rainbow', keywords: ['rainbow', 'weather', 'colorful'], category: 'Travel' },
  { emoji: '\u{2600}\u{FE0F}', name: 'sun', keywords: ['sun', 'sunny', 'weather'], category: 'Travel' },
  { emoji: '\u{2601}\u{FE0F}', name: 'cloud', keywords: ['cloud', 'weather'], category: 'Travel' },
  { emoji: '\u{26C5}', name: 'sun behind cloud', keywords: ['cloudy', 'weather'], category: 'Travel' },
  { emoji: '\u{1F327}\u{FE0F}', name: 'cloud with rain', keywords: ['rain', 'weather'], category: 'Travel' },
  { emoji: '\u{26C8}\u{FE0F}', name: 'thunder cloud rain', keywords: ['storm', 'thunder', 'weather'], category: 'Travel' },
  { emoji: '\u{2744}\u{FE0F}', name: 'snowflake', keywords: ['snow', 'cold', 'winter'], category: 'Travel' },
  { emoji: '\u{1F525}', name: 'fire', keywords: ['fire', 'hot', 'flame'], category: 'Travel' },
  { emoji: '\u{1F4A7}', name: 'droplet', keywords: ['water', 'drop', 'rain'], category: 'Travel' },
  { emoji: '\u{1F30A}', name: 'water wave', keywords: ['wave', 'ocean', 'sea'], category: 'Travel' },
  { emoji: '\u{2B50}', name: 'star', keywords: ['star', 'favorite', 'night'], category: 'Travel' },
  { emoji: '\u{1F319}', name: 'crescent moon', keywords: ['moon', 'night', 'crescent'], category: 'Travel' },

  // Activities (~55)
  { emoji: '\u{26BD}', name: 'soccer ball', keywords: ['soccer', 'football', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3C0}', name: 'basketball', keywords: ['basketball', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3C8}', name: 'american football', keywords: ['football', 'nfl', 'sport'], category: 'Activities' },
  { emoji: '\u{26BE}', name: 'baseball', keywords: ['baseball', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3BE}', name: 'tennis', keywords: ['tennis', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3D0}', name: 'volleyball', keywords: ['volleyball', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3B1}', name: 'pool 8 ball', keywords: ['billiard', 'pool', 'game'], category: 'Activities' },
  { emoji: '\u{1F3D3}', name: 'ping pong', keywords: ['table tennis', 'ping pong'], category: 'Activities' },
  { emoji: '\u{1F3B8}', name: 'guitar', keywords: ['guitar', 'music', 'rock'], category: 'Activities' },
  { emoji: '\u{1F3B5}', name: 'musical note', keywords: ['music', 'note', 'melody'], category: 'Activities' },
  { emoji: '\u{1F3B6}', name: 'musical notes', keywords: ['music', 'notes', 'melody'], category: 'Activities' },
  { emoji: '\u{1F3A4}', name: 'microphone', keywords: ['mic', 'karaoke', 'sing'], category: 'Activities' },
  { emoji: '\u{1F3A7}', name: 'headphone', keywords: ['headphone', 'music', 'listen'], category: 'Activities' },
  { emoji: '\u{1F3AC}', name: 'clapper board', keywords: ['movie', 'film', 'cinema'], category: 'Activities' },
  { emoji: '\u{1F3AE}', name: 'video game', keywords: ['game', 'gaming', 'controller'], category: 'Activities' },
  { emoji: '\u{1F3AF}', name: 'direct hit', keywords: ['target', 'bullseye', 'dart'], category: 'Activities' },
  { emoji: '\u{1F3B0}', name: 'slot machine', keywords: ['gambling', 'casino', 'slot'], category: 'Activities' },
  { emoji: '\u{1F3B2}', name: 'game die', keywords: ['dice', 'game', 'random'], category: 'Activities' },
  { emoji: '\u{265F}\u{FE0F}', name: 'chess pawn', keywords: ['chess', 'game', 'strategy'], category: 'Activities' },
  { emoji: '\u{1F3AD}', name: 'performing arts', keywords: ['theater', 'drama', 'mask'], category: 'Activities' },
  { emoji: '\u{1F3A8}', name: 'artist palette', keywords: ['art', 'paint', 'draw'], category: 'Activities' },
  { emoji: '\u{1F3C6}', name: 'trophy', keywords: ['trophy', 'win', 'champion'], category: 'Activities' },
  { emoji: '\u{1F3C5}', name: 'sports medal', keywords: ['medal', 'sports', 'winner'], category: 'Activities' },
  { emoji: '\u{1F947}', name: 'first place medal', keywords: ['gold', 'winner', 'first'], category: 'Activities' },
  { emoji: '\u{1F948}', name: 'second place medal', keywords: ['silver', 'second'], category: 'Activities' },
  { emoji: '\u{1F949}', name: 'third place medal', keywords: ['bronze', 'third'], category: 'Activities' },
  { emoji: '\u{1F3C3}', name: 'person running', keywords: ['run', 'exercise', 'sprint'], category: 'Activities' },
  { emoji: '\u{1F3CA}', name: 'person swimming', keywords: ['swim', 'pool', 'exercise'], category: 'Activities' },
  { emoji: '\u{1F6B4}', name: 'person biking', keywords: ['bike', 'cycling'], category: 'Activities' },
  { emoji: '\u{1F3CB}\u{FE0F}', name: 'person lifting', keywords: ['gym', 'weight', 'exercise'], category: 'Activities' },
  { emoji: '\u{1F93C}', name: 'people wrestling', keywords: ['wrestling', 'sport'], category: 'Activities' },
  { emoji: '\u{1F938}', name: 'person cartwheeling', keywords: ['gymnastics', 'acrobat'], category: 'Activities' },
  { emoji: '\u{26F3}', name: 'flag in hole', keywords: ['golf', 'sport'], category: 'Activities' },
  { emoji: '\u{1F3C4}', name: 'person surfing', keywords: ['surf', 'wave', 'ocean'], category: 'Activities' },
  { emoji: '\u{1F3A3}', name: 'fishing pole', keywords: ['fish', 'fishing'], category: 'Activities' },
  { emoji: '\u{1F3BF}', name: 'skis', keywords: ['ski', 'snow', 'winter'], category: 'Activities' },
  { emoji: '\u{26F7}\u{FE0F}', name: 'skier', keywords: ['ski', 'snow', 'winter'], category: 'Activities' },
  { emoji: '\u{1F3A9}', name: 'top hat', keywords: ['hat', 'formal', 'magic'], category: 'Activities' },
  { emoji: '\u{1F381}', name: 'wrapped gift', keywords: ['gift', 'present', 'birthday'], category: 'Activities' },
  { emoji: '\u{1F388}', name: 'balloon', keywords: ['balloon', 'party', 'birthday'], category: 'Activities' },
  { emoji: '\u{1F389}', name: 'party popper', keywords: ['party', 'celebration', 'tada'], category: 'Activities' },
  { emoji: '\u{1F38A}', name: 'confetti ball', keywords: ['confetti', 'celebration'], category: 'Activities' },
  { emoji: '\u{1F386}', name: 'fireworks', keywords: ['fireworks', 'celebration'], category: 'Activities' },
  { emoji: '\u{1F387}', name: 'sparkler', keywords: ['sparkler', 'firework'], category: 'Activities' },

  // Objects (~55)
  { emoji: '\u{1F4F1}', name: 'mobile phone', keywords: ['phone', 'smartphone', 'mobile'], category: 'Objects' },
  { emoji: '\u{1F4BB}', name: 'laptop', keywords: ['computer', 'laptop', 'mac'], category: 'Objects' },
  { emoji: '\u{1F4F7}', name: 'camera', keywords: ['camera', 'photo'], category: 'Objects' },
  { emoji: '\u{1F4FA}', name: 'television', keywords: ['tv', 'screen', 'monitor'], category: 'Objects' },
  { emoji: '\u{1F4FB}', name: 'radio', keywords: ['radio', 'audio'], category: 'Objects' },
  { emoji: '\u{231A}', name: 'watch', keywords: ['watch', 'time', 'clock'], category: 'Objects' },
  { emoji: '\u{23F0}', name: 'alarm clock', keywords: ['alarm', 'clock', 'morning'], category: 'Objects' },
  { emoji: '\u{1F4A1}', name: 'light bulb', keywords: ['idea', 'light', 'bulb'], category: 'Objects' },
  { emoji: '\u{1F50B}', name: 'battery', keywords: ['battery', 'power', 'energy'], category: 'Objects' },
  { emoji: '\u{1F50C}', name: 'electric plug', keywords: ['plug', 'electric', 'power'], category: 'Objects' },
  { emoji: '\u{1F4E7}', name: 'e-mail', keywords: ['email', 'mail', 'envelope'], category: 'Objects' },
  { emoji: '\u{1F4DD}', name: 'memo', keywords: ['memo', 'note', 'write'], category: 'Objects' },
  { emoji: '\u{1F4D6}', name: 'open book', keywords: ['book', 'read', 'study'], category: 'Objects' },
  { emoji: '\u{1F4DA}', name: 'books', keywords: ['books', 'library', 'study'], category: 'Objects' },
  { emoji: '\u{1F4D3}', name: 'notebook', keywords: ['notebook', 'journal'], category: 'Objects' },
  { emoji: '\u{1F4CB}', name: 'clipboard', keywords: ['clipboard', 'list'], category: 'Objects' },
  { emoji: '\u{1F4CA}', name: 'bar chart', keywords: ['chart', 'graph', 'stats'], category: 'Objects' },
  { emoji: '\u{1F4C8}', name: 'chart increasing', keywords: ['chart', 'growth', 'up'], category: 'Objects' },
  { emoji: '\u{1F4C9}', name: 'chart decreasing', keywords: ['chart', 'decline', 'down'], category: 'Objects' },
  { emoji: '\u{2702}\u{FE0F}', name: 'scissors', keywords: ['scissors', 'cut'], category: 'Objects' },
  { emoji: '\u{1F4CE}', name: 'paperclip', keywords: ['paperclip', 'attach'], category: 'Objects' },
  { emoji: '\u{1F4CC}', name: 'pushpin', keywords: ['pin', 'location'], category: 'Objects' },
  { emoji: '\u{1F4CF}', name: 'straight ruler', keywords: ['ruler', 'measure'], category: 'Objects' },
  { emoji: '\u{1F512}', name: 'locked', keywords: ['lock', 'secure', 'password'], category: 'Objects' },
  { emoji: '\u{1F513}', name: 'unlocked', keywords: ['unlock', 'open'], category: 'Objects' },
  { emoji: '\u{1F511}', name: 'key', keywords: ['key', 'password', 'unlock'], category: 'Objects' },
  { emoji: '\u{1F528}', name: 'hammer', keywords: ['hammer', 'tool', 'build'], category: 'Objects' },
  { emoji: '\u{1F527}', name: 'wrench', keywords: ['wrench', 'tool', 'fix'], category: 'Objects' },
  { emoji: '\u{1F529}', name: 'nut and bolt', keywords: ['nut', 'bolt', 'tool'], category: 'Objects' },
  { emoji: '\u{1F4E6}', name: 'package', keywords: ['box', 'package', 'delivery'], category: 'Objects' },
  { emoji: '\u{1F4B0}', name: 'money bag', keywords: ['money', 'rich', 'dollar'], category: 'Objects' },
  { emoji: '\u{1F4B5}', name: 'dollar banknote', keywords: ['money', 'dollar', 'cash'], category: 'Objects' },
  { emoji: '\u{1F4B3}', name: 'credit card', keywords: ['credit', 'card', 'payment'], category: 'Objects' },
  { emoji: '\u{1F48E}', name: 'gem stone', keywords: ['diamond', 'gem', 'jewel'], category: 'Objects' },
  { emoji: '\u{1F4E2}', name: 'loudspeaker', keywords: ['speaker', 'announcement'], category: 'Objects' },
  { emoji: '\u{1F514}', name: 'bell', keywords: ['bell', 'notification', 'ring'], category: 'Objects' },
  { emoji: '\u{1F50D}', name: 'magnifying glass left', keywords: ['search', 'find', 'zoom'], category: 'Objects' },
  { emoji: '\u{1F50E}', name: 'magnifying glass right', keywords: ['search', 'find', 'zoom'], category: 'Objects' },
  { emoji: '\u{1F6BF}', name: 'shower', keywords: ['shower', 'bath', 'water'], category: 'Objects' },
  { emoji: '\u{1F6BD}', name: 'toilet', keywords: ['toilet', 'bathroom', 'wc'], category: 'Objects' },
  { emoji: '\u{1F489}', name: 'syringe', keywords: ['syringe', 'medical', 'vaccine'], category: 'Objects' },
  { emoji: '\u{1F48A}', name: 'pill', keywords: ['pill', 'medicine', 'drug'], category: 'Objects' },

  // Symbols (~55)
  { emoji: '\u{2764}\u{FE0F}', name: 'red heart', keywords: ['heart', 'love', 'red'], category: 'Symbols' },
  { emoji: '\u{1F49B}', name: 'yellow heart', keywords: ['heart', 'love', 'yellow'], category: 'Symbols' },
  { emoji: '\u{1F49A}', name: 'green heart', keywords: ['heart', 'love', 'green'], category: 'Symbols' },
  { emoji: '\u{1F499}', name: 'blue heart', keywords: ['heart', 'love', 'blue'], category: 'Symbols' },
  { emoji: '\u{1F49C}', name: 'purple heart', keywords: ['heart', 'love', 'purple'], category: 'Symbols' },
  { emoji: '\u{1F5A4}', name: 'black heart', keywords: ['heart', 'love', 'black'], category: 'Symbols' },
  { emoji: '\u{1F494}', name: 'broken heart', keywords: ['heart', 'break', 'sad'], category: 'Symbols' },
  { emoji: '\u{1F495}', name: 'two hearts', keywords: ['hearts', 'love'], category: 'Symbols' },
  { emoji: '\u{1F496}', name: 'sparkling heart', keywords: ['heart', 'sparkle', 'love'], category: 'Symbols' },
  { emoji: '\u{1F497}', name: 'growing heart', keywords: ['heart', 'love', 'growing'], category: 'Symbols' },
  { emoji: '\u{1F498}', name: 'heart with arrow', keywords: ['heart', 'cupid', 'love'], category: 'Symbols' },
  { emoji: '\u{1F49D}', name: 'heart with ribbon', keywords: ['heart', 'gift', 'love'], category: 'Symbols' },
  { emoji: '\u{1F49E}', name: 'revolving hearts', keywords: ['hearts', 'love', 'romance'], category: 'Symbols' },
  { emoji: '\u{1F493}', name: 'beating heart', keywords: ['heart', 'beat', 'love'], category: 'Symbols' },
  { emoji: '\u{1F49F}', name: 'heart decoration', keywords: ['heart', 'decoration'], category: 'Symbols' },
  { emoji: '\u{2763}\u{FE0F}', name: 'heart exclamation', keywords: ['heart', 'exclamation'], category: 'Symbols' },
  { emoji: '\u{274C}', name: 'cross mark', keywords: ['no', 'wrong', 'cancel', 'x'], category: 'Symbols' },
  { emoji: '\u{2705}', name: 'check mark', keywords: ['yes', 'correct', 'done', 'check'], category: 'Symbols' },
  { emoji: '\u{2714}\u{FE0F}', name: 'heavy check mark', keywords: ['check', 'done', 'yes'], category: 'Symbols' },
  { emoji: '\u{2716}\u{FE0F}', name: 'heavy multiplication', keywords: ['cancel', 'wrong', 'x'], category: 'Symbols' },
  { emoji: '\u{2795}', name: 'plus', keywords: ['plus', 'add', 'math'], category: 'Symbols' },
  { emoji: '\u{2796}', name: 'minus', keywords: ['minus', 'subtract', 'math'], category: 'Symbols' },
  { emoji: '\u{2797}', name: 'division', keywords: ['divide', 'math'], category: 'Symbols' },
  { emoji: '\u{27B0}', name: 'curly loop', keywords: ['loop', 'curl'], category: 'Symbols' },
  { emoji: '\u{2757}', name: 'exclamation mark', keywords: ['exclamation', 'warning', 'alert'], category: 'Symbols' },
  { emoji: '\u{2753}', name: 'question mark', keywords: ['question', 'what', 'help'], category: 'Symbols' },
  { emoji: '\u{2049}\u{FE0F}', name: 'exclamation question', keywords: ['surprise', 'interrobang'], category: 'Symbols' },
  { emoji: '\u{1F4AF}', name: 'hundred points', keywords: ['hundred', 'perfect', 'score'], category: 'Symbols' },
  { emoji: '\u{1F4A2}', name: 'anger symbol', keywords: ['angry', 'rage'], category: 'Symbols' },
  { emoji: '\u{1F4A5}', name: 'collision', keywords: ['boom', 'explosion', 'crash'], category: 'Symbols' },
  { emoji: '\u{1F4AB}', name: 'dizzy', keywords: ['dizzy', 'star', 'sparkle'], category: 'Symbols' },
  { emoji: '\u{1F4AC}', name: 'speech balloon', keywords: ['speech', 'talk', 'chat'], category: 'Symbols' },
  { emoji: '\u{1F4AD}', name: 'thought balloon', keywords: ['thought', 'think'], category: 'Symbols' },
  { emoji: '\u{1F4A4}', name: 'zzz', keywords: ['sleep', 'zzz', 'tired'], category: 'Symbols' },
  { emoji: '\u{267B}\u{FE0F}', name: 'recycling symbol', keywords: ['recycle', 'environment'], category: 'Symbols' },
  { emoji: '\u{269B}\u{FE0F}', name: 'atom symbol', keywords: ['atom', 'science'], category: 'Symbols' },
  { emoji: '\u{2622}\u{FE0F}', name: 'radioactive', keywords: ['radioactive', 'nuclear', 'danger'], category: 'Symbols' },
  { emoji: '\u{2623}\u{FE0F}', name: 'biohazard', keywords: ['biohazard', 'danger'], category: 'Symbols' },
  { emoji: '\u{262F}\u{FE0F}', name: 'yin yang', keywords: ['yin yang', 'balance'], category: 'Symbols' },
  { emoji: '\u{1F195}', name: 'new button', keywords: ['new', 'button'], category: 'Symbols' },
  { emoji: '\u{1F197}', name: 'ok button', keywords: ['ok', 'button'], category: 'Symbols' },
  { emoji: '\u{1F199}', name: 'up button', keywords: ['up', 'button'], category: 'Symbols' },
  { emoji: '\u{1F192}', name: 'cool button', keywords: ['cool', 'button'], category: 'Symbols' },
  { emoji: '\u{1F193}', name: 'free button', keywords: ['free', 'button'], category: 'Symbols' },
  { emoji: '\u{1F500}', name: 'shuffle tracks', keywords: ['shuffle', 'random'], category: 'Symbols' },
  { emoji: '\u{1F501}', name: 'repeat', keywords: ['repeat', 'loop'], category: 'Symbols' },
  { emoji: '\u{1F502}', name: 'repeat single', keywords: ['repeat', 'single', 'one'], category: 'Symbols' },
  { emoji: '\u{25B6}\u{FE0F}', name: 'play button', keywords: ['play', 'start'], category: 'Symbols' },
  { emoji: '\u{23F8}\u{FE0F}', name: 'pause button', keywords: ['pause', 'stop'], category: 'Symbols' },
  { emoji: '\u{23F9}\u{FE0F}', name: 'stop button', keywords: ['stop', 'end'], category: 'Symbols' },

  // Flags (~45)
  { emoji: '\u{1F1EF}\u{1F1F5}', name: 'Japan', keywords: ['japan', 'japanese', 'jp'], category: 'Flags' },
  { emoji: '\u{1F1FA}\u{1F1F8}', name: 'United States', keywords: ['usa', 'america', 'us'], category: 'Flags' },
  { emoji: '\u{1F1EC}\u{1F1E7}', name: 'United Kingdom', keywords: ['uk', 'britain', 'gb'], category: 'Flags' },
  { emoji: '\u{1F1EB}\u{1F1F7}', name: 'France', keywords: ['france', 'french', 'fr'], category: 'Flags' },
  { emoji: '\u{1F1E9}\u{1F1EA}', name: 'Germany', keywords: ['germany', 'german', 'de'], category: 'Flags' },
  { emoji: '\u{1F1EE}\u{1F1F9}', name: 'Italy', keywords: ['italy', 'italian', 'it'], category: 'Flags' },
  { emoji: '\u{1F1EA}\u{1F1F8}', name: 'Spain', keywords: ['spain', 'spanish', 'es'], category: 'Flags' },
  { emoji: '\u{1F1F0}\u{1F1F7}', name: 'South Korea', keywords: ['korea', 'korean', 'kr'], category: 'Flags' },
  { emoji: '\u{1F1E8}\u{1F1F3}', name: 'China', keywords: ['china', 'chinese', 'cn'], category: 'Flags' },
  { emoji: '\u{1F1F7}\u{1F1FA}', name: 'Russia', keywords: ['russia', 'russian', 'ru'], category: 'Flags' },
  { emoji: '\u{1F1E7}\u{1F1F7}', name: 'Brazil', keywords: ['brazil', 'brazilian', 'br'], category: 'Flags' },
  { emoji: '\u{1F1E6}\u{1F1FA}', name: 'Australia', keywords: ['australia', 'au'], category: 'Flags' },
  { emoji: '\u{1F1E8}\u{1F1E6}', name: 'Canada', keywords: ['canada', 'ca'], category: 'Flags' },
  { emoji: '\u{1F1EE}\u{1F1F3}', name: 'India', keywords: ['india', 'indian', 'in'], category: 'Flags' },
  { emoji: '\u{1F1F2}\u{1F1FD}', name: 'Mexico', keywords: ['mexico', 'mexican', 'mx'], category: 'Flags' },
  { emoji: '\u{1F1F9}\u{1F1ED}', name: 'Thailand', keywords: ['thailand', 'thai', 'th'], category: 'Flags' },
  { emoji: '\u{1F1F8}\u{1F1EC}', name: 'Singapore', keywords: ['singapore', 'sg'], category: 'Flags' },
  { emoji: '\u{1F1F9}\u{1F1FC}', name: 'Taiwan', keywords: ['taiwan', 'tw'], category: 'Flags' },
  { emoji: '\u{1F1F3}\u{1F1FF}', name: 'New Zealand', keywords: ['new zealand', 'nz'], category: 'Flags' },
  { emoji: '\u{1F1F8}\u{1F1EA}', name: 'Sweden', keywords: ['sweden', 'swedish', 'se'], category: 'Flags' },
  { emoji: '\u{1F1F3}\u{1F1F4}', name: 'Norway', keywords: ['norway', 'norwegian', 'no'], category: 'Flags' },
  { emoji: '\u{1F1E8}\u{1F1ED}', name: 'Switzerland', keywords: ['switzerland', 'swiss', 'ch'], category: 'Flags' },
  { emoji: '\u{1F1F3}\u{1F1F1}', name: 'Netherlands', keywords: ['netherlands', 'dutch', 'nl'], category: 'Flags' },
  { emoji: '\u{1F1F5}\u{1F1F9}', name: 'Portugal', keywords: ['portugal', 'portuguese', 'pt'], category: 'Flags' },
  { emoji: '\u{1F1F5}\u{1F1ED}', name: 'Philippines', keywords: ['philippines', 'ph'], category: 'Flags' },
  { emoji: '\u{1F1EE}\u{1F1E9}', name: 'Indonesia', keywords: ['indonesia', 'id'], category: 'Flags' },
  { emoji: '\u{1F1FB}\u{1F1F3}', name: 'Vietnam', keywords: ['vietnam', 'vietnamese', 'vn'], category: 'Flags' },
  { emoji: '\u{1F1F2}\u{1F1FE}', name: 'Malaysia', keywords: ['malaysia', 'my'], category: 'Flags' },
  { emoji: '\u{1F1E6}\u{1F1F7}', name: 'Argentina', keywords: ['argentina', 'ar'], category: 'Flags' },
  { emoji: '\u{1F1F5}\u{1F1F1}', name: 'Poland', keywords: ['poland', 'polish', 'pl'], category: 'Flags' },
  { emoji: '\u{1F1F9}\u{1F1F7}', name: 'Turkey', keywords: ['turkey', 'turkish', 'tr'], category: 'Flags' },
  { emoji: '\u{1F1E6}\u{1F1EA}', name: 'UAE', keywords: ['uae', 'emirates', 'ae'], category: 'Flags' },
  { emoji: '\u{1F1F8}\u{1F1E6}', name: 'Saudi Arabia', keywords: ['saudi', 'arabia', 'sa'], category: 'Flags' },
  { emoji: '\u{1F1EE}\u{1F1F1}', name: 'Israel', keywords: ['israel', 'il'], category: 'Flags' },
  { emoji: '\u{1F1EA}\u{1F1EC}', name: 'Egypt', keywords: ['egypt', 'eg'], category: 'Flags' },
  { emoji: '\u{1F1FF}\u{1F1E6}', name: 'South Africa', keywords: ['south africa', 'za'], category: 'Flags' },
  { emoji: '\u{1F1F3}\u{1F1EC}', name: 'Nigeria', keywords: ['nigeria', 'ng'], category: 'Flags' },
  { emoji: '\u{1F1F0}\u{1F1EA}', name: 'Kenya', keywords: ['kenya', 'ke'], category: 'Flags' },
  { emoji: '\u{1F3F3}\u{FE0F}', name: 'white flag', keywords: ['flag', 'white', 'surrender'], category: 'Flags' },
  { emoji: '\u{1F3F4}', name: 'black flag', keywords: ['flag', 'black'], category: 'Flags' },
  { emoji: '\u{1F3C1}', name: 'chequered flag', keywords: ['flag', 'finish', 'race'], category: 'Flags' },
  { emoji: '\u{1F6A9}', name: 'triangular flag', keywords: ['flag', 'location'], category: 'Flags' },
  { emoji: '\u{1F3F3}\u{FE0F}\u{200D}\u{1F308}', name: 'rainbow flag', keywords: ['rainbow', 'pride', 'lgbtq'], category: 'Flags' },
];

/**
 * Search emojis by query string (matches name and keywords).
 */
export function searchEmojis(query: string): Emoji[] {
  if (!query.trim()) return EMOJI_DATABASE;
  const lower = query.toLowerCase();
  return EMOJI_DATABASE.filter(
    (e) =>
      e.name.toLowerCase().includes(lower) ||
      e.keywords.some((k) => k.toLowerCase().includes(lower))
  );
}

/**
 * Filter emojis by category.
 */
export function filterByCategory(category: EmojiCategory): Emoji[] {
  return EMOJI_DATABASE.filter((e) => e.category === category);
}

const RECENT_KEY = 'emoji-search-recent';
const MAX_RECENT = 24;

/**
 * Get recently used emojis from localStorage.
 */
export function getRecentEmojis(): string[] {
  try {
    const stored = localStorage.getItem(RECENT_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch {
    return [];
  }
}

/**
 * Add an emoji to recent list in localStorage.
 */
export function addRecentEmoji(emoji: string): void {
  try {
    const recent = getRecentEmojis().filter((e) => e !== emoji);
    recent.unshift(emoji);
    localStorage.setItem(RECENT_KEY, JSON.stringify(recent.slice(0, MAX_RECENT)));
  } catch {
    // localStorage unavailable
  }
}
