export type AppCategory =
  | 'Text'
  | 'Encode'
  | 'Crypto'
  | 'Number'
  | 'DateTime'
  | 'JSON'
  | 'Code'
  | 'Color / CSS'
  | 'Image'
  | 'PDF'
  | 'Video'
  | 'Generator'
  | 'Network';

export interface AppInfo {
  path: string;
  icon: string;
  displayName: string;
  description: string;
  category: AppCategory;
}

export const CATEGORY_ICONS: Record<AppCategory, string> = {
  Text: '📝',
  Encode: '🔤',
  Crypto: '🔐',
  Number: '🔢',
  DateTime: '📅',
  JSON: '{}',
  Code: '💻',
  'Color / CSS': '🎨',
  Image: '🖼',
  PDF: '📄',
  Video: '🎬',
  Generator: '⚙',
  Network: '🌐',
};

export const CATEGORY_COLORS: Record<AppCategory, string> = {
  Text: 'bg-blue-500',
  Encode: 'bg-indigo-500',
  Crypto: 'bg-purple-500',
  Number: 'bg-pink-500',
  DateTime: 'bg-orange-500',
  JSON: 'bg-yellow-600',
  Code: 'bg-green-500',
  'Color / CSS': 'bg-rose-500',
  Image: 'bg-teal-500',
  PDF: 'bg-red-500',
  Video: 'bg-violet-500',
  Generator: 'bg-cyan-500',
  Network: 'bg-emerald-500',
};

export const APPS: AppInfo[] = [
  // Text
  { path: '/text-counter', icon: '📝', displayName: 'Text Counter', description: '文字数・単語数・行数をリアルタイムカウント', category: 'Text' },
  { path: '/text-deduplicate', icon: '🔀', displayName: 'Text Deduplicate', description: 'テキストの重複行を削除', category: 'Text' },
  { path: '/text-diff-checker', icon: '🔍', displayName: 'Text Diff Checker', description: '2つのテキストの差分を比較表示', category: 'Text' },
  { path: '/text-case-converter', icon: '🔤', displayName: 'Text Case Converter', description: '大文字/小文字変換', category: 'Text' },
  { path: '/text-code-case', icon: '🐍', displayName: 'Code Case Converter', description: 'camelCase, snake_case等の命名規則変換', category: 'Text' },
  { path: '/text-reverse', icon: '🔄', displayName: 'Text Reverse', description: 'テキスト逆順変換', category: 'Text' },
  { path: '/text-sort', icon: '📊', displayName: 'Text Sort', description: 'テキスト行ソート', category: 'Text' },
  { path: '/text-replace', icon: '🔁', displayName: 'Text Replace', description: 'テキスト検索・置換', category: 'Text' },
  { path: '/text-line-number', icon: '🔢', displayName: 'Line Number', description: '行番号付与', category: 'Text' },
  { path: '/text-prefix-suffix', icon: '📎', displayName: 'Prefix Suffix', description: 'プレフィックス・サフィックス追加', category: 'Text' },
  { path: '/text-slugify', icon: '🔗', displayName: 'Slugify', description: 'URLスラッグ生成', category: 'Text' },
  { path: '/text-lorem-ipsum', icon: '📄', displayName: 'Lorem Ipsum', description: 'ダミーテキスト生成', category: 'Text' },
  { path: '/text-word-frequency', icon: '📈', displayName: 'Word Frequency', description: '単語出現頻度解析', category: 'Text' },
  { path: '/text-fullwidth-halfwidth', icon: 'Ａ', displayName: 'Fullwidth Halfwidth', description: '全角・半角変換', category: 'Text' },
  { path: '/text-kana-converter', icon: 'あ', displayName: 'Kana Converter', description: 'ひらがな・カタカナ変換', category: 'Text' },
  { path: '/text-bionic-reading', icon: '👁', displayName: 'Bionic Reading', description: 'Bionic Reading変換', category: 'Text' },
  { path: '/text-markdown-html', icon: '📑', displayName: 'Markdown to HTML', description: 'Markdown→HTML変換', category: 'Text' },
  { path: '/text-markdown-preview', icon: '👀', displayName: 'Markdown Preview', description: 'Markdownプレビュー', category: 'Text' },
  { path: '/alt-text-helper', icon: '♿', displayName: 'Alt Text Helper', description: 'Image alt text decision tree helper', category: 'Text' },
  { path: '/aria-reference', icon: '♿', displayName: 'ARIA Reference', description: 'WAI-ARIAロール・ステート・プロパティリファレンス', category: 'Text' },
  { path: '/homoglyph-detector', icon: '🔍', displayName: 'Homoglyph Detector', description: '見た目の似た文字(ホモグリフ)を検出', category: 'Text' },
  { path: '/text-columns', icon: '📋', displayName: 'Text Columns', description: 'テキストを列に変換・整列', category: 'Text' },
  { path: '/text-emoji-search', icon: '😀', displayName: 'Emoji Search', description: '絵文字を名前・カテゴリで検索', category: 'Text' },
  { path: '/text-encryption', icon: '🔐', displayName: 'Text Encryption', description: 'テキストを暗号化・復号化', category: 'Text' },
  { path: '/text-invisible-chars', icon: '👻', displayName: 'Invisible Chars Detector', description: '不可視文字を検出・表示', category: 'Text' },
  { path: '/text-readability', icon: '📊', displayName: 'Text Readability', description: '文章の読みやすさスコアを計算', category: 'Text' },
  { path: '/text-reading-time', icon: '⏱', displayName: 'Reading Time', description: 'テキストの読了時間を推定', category: 'Text' },
  { path: '/text-ruby', icon: 'あ', displayName: 'Text Ruby Generator', description: 'テキストにルビ(振り仮名)を付与', category: 'Text' },
  { path: '/text-speech', icon: '🔊', displayName: 'Text to Speech', description: 'テキストを音声に変換', category: 'Text' },
  { path: '/text-vertical', icon: '📏', displayName: 'Text Vertical', description: 'テキストを縦書きに変換', category: 'Text' },
  { path: '/list-to-table', icon: '📋', displayName: 'List to Table', description: 'リストをテーブルに変換', category: 'Text' },
  { path: '/nato-phonetic', icon: '📡', displayName: 'NATO Phonetic Alphabet', description: 'NATOフォネティックアルファベット変換', category: 'Text' },

  // Encode
  { path: '/url-encoder', icon: '🔗', displayName: 'URL Encoder', description: 'URLエンコード・デコード', category: 'Encode' },
  { path: '/encode-base64-string', icon: '🔤', displayName: 'Base64 Encoder', description: 'Base64文字列エンコード・デコード', category: 'Encode' },
  { path: '/encode-base64-file', icon: '📁', displayName: 'Base64 File', description: 'ファイルBase64変換', category: 'Encode' },
  { path: '/encode-base32', icon: '🔡', displayName: 'Base32 Encoder', description: 'Base32エンコード・デコード', category: 'Encode' },
  { path: '/encode-binary', icon: '💻', displayName: 'Binary Converter', description: 'テキスト-バイナリ変換', category: 'Encode' },
  { path: '/encode-html-entity', icon: '&', displayName: 'HTML Entity', description: 'HTMLエンティティ変換', category: 'Encode' },
  { path: '/encode-morse', icon: '📡', displayName: 'Morse Code', description: 'モールス符号変換', category: 'Encode' },
  { path: '/encode-punycode', icon: '🌐', displayName: 'Punycode', description: 'Punycode変換', category: 'Encode' },
  { path: '/encode-unicode', icon: '🔣', displayName: 'Unicode Escape', description: 'Unicodeエスケープ変換', category: 'Encode' },
  { path: '/uuencode', icon: '📦', displayName: 'UUEncode', description: 'UUEncode/UUDecode', category: 'Encode' },
  { path: '/charset-detector', icon: '🔍', displayName: 'Charset Detector', description: '文字エンコーディングを検出', category: 'Encode' },
  { path: '/csv-to-json', icon: '🔄', displayName: 'CSV to JSON', description: 'CSV→JSON変換', category: 'Encode' },
  { path: '/html-to-markdown', icon: '📝', displayName: 'HTML to Markdown', description: 'HTML→Markdown変換', category: 'Encode' },
  { path: '/toml-to-json', icon: '🔄', displayName: 'TOML to JSON', description: 'TOML→JSON変換', category: 'Encode' },
  { path: '/toml-validator', icon: '✅', displayName: 'TOML Validator', description: 'TOML形式を検証', category: 'Encode' },
  { path: '/xml-to-json', icon: '🔄', displayName: 'XML to JSON', description: 'XML→JSON変換', category: 'Encode' },
  { path: '/yaml-to-json', icon: '🔄', displayName: 'YAML to JSON', description: 'YAML→JSON変換', category: 'Encode' },
  { path: '/yaml-validator', icon: '✅', displayName: 'YAML Validator', description: 'YAML形式を検証', category: 'Encode' },
  { path: '/unicode-inspector', icon: '🔣', displayName: 'Unicode Inspector', description: 'Unicodeコードポイントを詳細表示', category: 'Encode' },

  // Crypto
  { path: '/hash-md5', icon: '#', displayName: 'MD5 Hash', description: 'MD5ハッシュ生成', category: 'Crypto' },
  { path: '/hash-sha1', icon: '#', displayName: 'SHA-1 Hash', description: 'SHA-1ハッシュ生成', category: 'Crypto' },
  { path: '/hash-sha256', icon: '#', displayName: 'SHA Hash', description: 'SHA-256/384/512ハッシュ生成', category: 'Crypto' },
  { path: '/hash-crc32', icon: '✅', displayName: 'CRC32', description: 'CRC32チェックサム', category: 'Crypto' },
  { path: '/hash-hmac', icon: '🔑', displayName: 'HMAC Generator', description: 'HMAC認証コード生成', category: 'Crypto' },
  { path: '/aes-encrypt', icon: '🔐', displayName: 'AES Encrypt', description: 'AES-256-GCM暗号化・復号化', category: 'Crypto' },
  { path: '/des-encrypt', icon: '🔐', displayName: 'DES Encrypt', description: 'Triple DES暗号化・復号化', category: 'Crypto' },
  { path: '/bcrypt-hash', icon: '🔒', displayName: 'Bcrypt Hash', description: 'Bcryptハッシュ生成・検証', category: 'Crypto' },
  { path: '/rsa-keygen', icon: '🗝', displayName: 'RSA Key Generator', description: 'RSA鍵ペア生成', category: 'Crypto' },
  { path: '/crypto-caesar', icon: '🏛', displayName: 'Caesar Cipher', description: 'シーザー暗号', category: 'Crypto' },
  { path: '/crypto-rot13', icon: '🔄', displayName: 'ROT13', description: 'ROT13変換', category: 'Crypto' },
  { path: '/crypto-vigenere', icon: '📜', displayName: 'Vigenere Cipher', description: 'ヴィジュネル暗号', category: 'Crypto' },
  { path: '/crypto-atbash', icon: '🪞', displayName: 'Atbash Cipher', description: 'アトバシュ暗号', category: 'Crypto' },
  { path: '/crypto-affine', icon: '🔢', displayName: 'Affine Cipher', description: 'アフィン暗号', category: 'Crypto' },
  { path: '/crypto-rail-fence', icon: '🚂', displayName: 'Rail Fence Cipher', description: 'レールフェンス暗号', category: 'Crypto' },
  { path: '/enigma-cipher', icon: '⚙', displayName: 'Enigma Cipher', description: 'Enigma暗号シミュレーター', category: 'Crypto' },
  { path: '/file-hash-checker', icon: '#', displayName: 'File Hash Checker', description: 'ファイルのハッシュ値を検証', category: 'Crypto' },
  { path: '/secret-redactor', icon: '🔒', displayName: 'Secret Redactor', description: '機密情報をマスク・削除', category: 'Crypto' },
  { path: '/sri-hash-generator', icon: '#', displayName: 'SRI Hash Generator', description: 'Subresource Integrity ハッシュ生成', category: 'Crypto' },
  { path: '/ssl-cert-decoder', icon: '🔓', displayName: 'SSL Cert Decoder', description: 'SSL証明書をデコード・解析', category: 'Crypto' },
  { path: '/totp-generator', icon: '🔑', displayName: 'TOTP Generator', description: 'TOTP(時刻ベースワンタイムパスワード)生成', category: 'Crypto' },

  // Number
  { path: '/number-base-converter', icon: '🔢', displayName: 'Base Converter', description: '2進/8進/10進/16進数変換', category: 'Number' },
  { path: '/number-fraction', icon: '➗', displayName: 'Fraction', description: '小数→分数変換', category: 'Number' },
  { path: '/number-kanji', icon: '漢', displayName: 'Kanji Number', description: '漢数字変換', category: 'Number' },
  { path: '/math-calculator', icon: '🧮', displayName: 'Calculator', description: '電卓', category: 'Number' },
  { path: '/math-percentage', icon: '%', displayName: 'Percentage', description: '割合・パーセント計算', category: 'Number' },
  { path: '/math-statistics', icon: '📊', displayName: 'Statistics', description: '統計計算', category: 'Number' },
  { path: '/math-area', icon: '📐', displayName: 'Area Calculator', description: '面積計算', category: 'Number' },
  { path: '/unit-converter', icon: '⚖', displayName: 'Unit Converter', description: '単位変換', category: 'Number' },
  { path: '/random-number', icon: '🎲', displayName: 'Random Number', description: '乱数生成', category: 'Number' },
  { path: '/random-dice', icon: '🎲', displayName: 'Dice Roller', description: 'サイコロシミュレーター', category: 'Number' },
  { path: '/random-coin', icon: '🪙', displayName: 'Coin Flip', description: 'コイン投げシミュレーター', category: 'Number' },
  { path: '/aspect-ratio-calculator', icon: '📐', displayName: 'Aspect Ratio Calculator', description: 'アスペクト比を計算・変換', category: 'Number' },
  { path: '/boolean-algebra', icon: '⊕', displayName: 'Boolean Algebra', description: 'ブール代数計算・真理値表生成', category: 'Number' },
  { path: '/compound-interest', icon: '📈', displayName: 'Compound Interest', description: '複利計算シミュレーター', category: 'Number' },
  { path: '/currency-converter', icon: '💱', displayName: 'Currency Converter', description: '通貨換算', category: 'Number' },
  { path: '/discount-calculator', icon: '%', displayName: 'Discount Calculator', description: '割引価格計算', category: 'Number' },
  { path: '/fibonacci-generator', icon: '🔢', displayName: 'Fibonacci Generator', description: 'フィボナッチ数列生成', category: 'Number' },
  { path: '/file-size-converter', icon: '💾', displayName: 'File Size Converter', description: 'ファイルサイズ単位変換', category: 'Number' },
  { path: '/gcd-lcm', icon: '➗', displayName: 'GCD / LCM Calculator', description: '最大公約数・最小公倍数計算', category: 'Number' },
  { path: '/loan-calculator', icon: '🏦', displayName: 'Loan Calculator', description: 'ローン返済シミュレーター', category: 'Number' },
  { path: '/matrix-calculator', icon: '🔢', displayName: 'Matrix Calculator', description: '行列計算', category: 'Number' },
  { path: '/prime-checker', icon: '🔢', displayName: 'Prime Checker', description: '素数判定・素因数分解', category: 'Number' },
  { path: '/roman-numeral', icon: 'Ⅹ', displayName: 'Roman Numeral Converter', description: 'ローマ数字変換', category: 'Number' },
  { path: '/spacing-calculator', icon: '📐', displayName: 'Spacing Calculator', description: 'スペーシング計算', category: 'Number' },
  { path: '/tax-calculator', icon: '🧾', displayName: 'Tax Calculator', description: '消費税計算', category: 'Number' },
  { path: '/tip-calculator', icon: '💰', displayName: 'Tip Calculator', description: 'チップ・割り勘計算', category: 'Number' },
  { path: '/unit-converter-advanced', icon: '⚖', displayName: 'Unit Converter Advanced', description: '高度な単位変換', category: 'Number' },
  { path: '/periodic-table', icon: '⚗', displayName: 'Periodic Table', description: '元素周期表', category: 'Number' },

  // DateTime
  { path: '/datetime-unix', icon: '🕐', displayName: 'Unix Timestamp', description: 'UNIXタイムスタンプ変換', category: 'DateTime' },
  { path: '/datetime-iso8601', icon: '📅', displayName: 'ISO 8601', description: 'ISO 8601形式変換', category: 'DateTime' },
  { path: '/datetime-rfc2822', icon: '📧', displayName: 'RFC 2822', description: 'RFC 2822形式変換', category: 'DateTime' },
  { path: '/datetime-diff', icon: '📏', displayName: 'Date Diff', description: '日付差分計算', category: 'DateTime' },
  { path: '/datetime-wareki', icon: '🏯', displayName: 'Wareki Converter', description: '和暦変換', category: 'DateTime' },
  { path: '/datetime-world-clock', icon: '🌍', displayName: 'World Clock', description: '世界時計', category: 'DateTime' },
  { path: '/datetime-countdown', icon: '⏳', displayName: 'Countdown', description: 'カウントダウン', category: 'DateTime' },
  { path: '/datetime-timer', icon: '⏱', displayName: 'Timer', description: 'タイマー', category: 'DateTime' },
  { path: '/datetime-stopwatch', icon: '⏱', displayName: 'Stopwatch', description: 'ストップウォッチ', category: 'DateTime' },
  { path: '/datetime-crontab', icon: '⚙', displayName: 'Crontab', description: 'Cron式生成・パース', category: 'DateTime' },
  { path: '/datetime-eta', icon: '🚀', displayName: 'ETA Calculator', description: '到着予想時刻計算', category: 'DateTime' },
  { path: '/ical-parser', icon: '📅', displayName: 'iCalendar Parser', description: 'iCalendar(.ics)ファイルを解析', category: 'DateTime' },
  { path: '/pomodoro-timer', icon: '🍅', displayName: 'Pomodoro Timer', description: 'ポモドーロタイマー', category: 'DateTime' },
  { path: '/timezone-converter', icon: '🌍', displayName: 'Timezone Converter', description: 'タイムゾーン変換', category: 'DateTime' },
  { path: '/working-days-calculator', icon: '📅', displayName: 'Working Days Calculator', description: '営業日計算', category: 'DateTime' },

  // JSON
  { path: '/json-formatter', icon: '{}', displayName: 'JSON Formatter', description: 'JSON整形', category: 'JSON' },
  { path: '/json-minify', icon: '📦', displayName: 'JSON Minify', description: 'JSON圧縮', category: 'JSON' },
  { path: '/json-validator', icon: '✅', displayName: 'JSON Validator', description: 'JSON検証', category: 'JSON' },
  { path: '/json-viewer', icon: '🌳', displayName: 'JSON Viewer', description: 'JSONツリービュー', category: 'JSON' },
  { path: '/json-editor', icon: '✏', displayName: 'JSON Editor', description: 'JSONエディタ', category: 'JSON' },
  { path: '/json-diff', icon: '🔍', displayName: 'JSON Diff', description: 'JSON差分比較', category: 'JSON' },
  { path: '/json-to-csv', icon: '📊', displayName: 'JSON to CSV', description: 'JSON→CSV変換', category: 'JSON' },
  { path: '/json-to-yaml', icon: '📝', displayName: 'JSON to YAML', description: 'JSON→YAML変換', category: 'JSON' },
  { path: '/json-to-xml', icon: '📄', displayName: 'JSON to XML', description: 'JSON→XML変換', category: 'JSON' },
  { path: '/json-to-toml', icon: '⚙', displayName: 'JSON to TOML', description: 'JSON→TOML変換', category: 'JSON' },
  { path: '/json-to-table', icon: '📋', displayName: 'JSON to Table', description: 'JSON→テーブル変換', category: 'JSON' },
  { path: '/jsonpath-tester', icon: '🎯', displayName: 'JSONPath Tester', description: 'JSONPath式テスト', category: 'JSON' },
  { path: '/json-schema-generator', icon: '{}', displayName: 'JSON Schema Generator', description: 'JSONからスキーマを生成', category: 'JSON' },
  { path: '/protobuf-to-json', icon: '🔄', displayName: 'Protobuf to JSON', description: 'Protobuf→JSON変換', category: 'JSON' },
  { path: '/sql-to-json-schema', icon: '🔄', displayName: 'SQL to JSON Schema', description: 'SQL DDL→JSONスキーマ変換', category: 'JSON' },

  // Code
  { path: '/html-formatter', icon: '🌐', displayName: 'HTML Formatter', description: 'HTML整形', category: 'Code' },
  { path: '/html-minifier', icon: '📦', displayName: 'HTML Minifier', description: 'HTML圧縮', category: 'Code' },
  { path: '/css-formatter', icon: '🎨', displayName: 'CSS Formatter', description: 'CSS整形', category: 'Code' },
  { path: '/css-minifier', icon: '📦', displayName: 'CSS Minifier', description: 'CSS圧縮', category: 'Code' },
  { path: '/scss-formatter', icon: '🎨', displayName: 'SCSS Formatter', description: 'SCSS整形', category: 'Code' },
  { path: '/js-formatter', icon: '📜', displayName: 'JS Formatter', description: 'JavaScript整形', category: 'Code' },
  { path: '/js-minifier', icon: '📦', displayName: 'JS Minifier', description: 'JavaScript圧縮', category: 'Code' },
  { path: '/ts-formatter', icon: '📘', displayName: 'TypeScript Formatter', description: 'TypeScript整形', category: 'Code' },
  { path: '/sql-formatter', icon: '🗃', displayName: 'SQL Formatter', description: 'SQL整形・圧縮', category: 'Code' },
  { path: '/xml-formatter', icon: '📄', displayName: 'XML Formatter', description: 'XML整形・圧縮', category: 'Code' },
  { path: '/yaml-formatter', icon: '📝', displayName: 'YAML Formatter', description: 'YAML整形', category: 'Code' },
  { path: '/graphql-formatter', icon: '◆', displayName: 'GraphQL Formatter', description: 'GraphQL整形・圧縮', category: 'Code' },
  { path: '/syntax-highlight', icon: '🌈', displayName: 'Syntax Highlighter', description: 'シンタックスハイライト', category: 'Code' },
  { path: '/code-diff-viewer', icon: '🔍', displayName: 'Diff Viewer', description: '差分ビューアー', category: 'Code' },
  { path: '/code-http-status', icon: '🌐', displayName: 'HTTP Status', description: 'HTTPステータスコード一覧', category: 'Code' },
  { path: '/code-jwt-decoder', icon: '🔓', displayName: 'JWT Decoder', description: 'JWTデコード', category: 'Code' },
  { path: '/code-regex-tester', icon: '🔎', displayName: 'Regex Tester', description: '正規表現テスト', category: 'Code' },
  { path: '/code-chmod', icon: '🔧', displayName: 'Chmod Calculator', description: 'chmod計算', category: 'Code' },
  { path: '/code-to-image', icon: '📸', displayName: 'Code to Image', description: 'コード→画像変換', category: 'Code' },
  { path: '/docker-compose-converter', icon: '🐳', displayName: 'Docker Run to Compose', description: 'docker run→compose変換', category: 'Code' },
  { path: '/docker-run-to-compose', icon: '🐳', displayName: 'Docker Run to Compose v2', description: 'docker run→compose変換(v2)', category: 'Code' },
  { path: '/git-cheatsheet', icon: '📖', displayName: 'Git Cheatsheet', description: 'Gitチートシート', category: 'Code' },
  { path: '/changelog-generator', icon: '📝', displayName: 'Changelog Generator', description: 'CHANGELOG.md生成', category: 'Code' },
  { path: '/code-snippet-manager', icon: '📋', displayName: 'Code Snippet Manager', description: 'コードスニペット管理', category: 'Code' },
  { path: '/dockerfile-generator', icon: '🐳', displayName: 'Dockerfile Generator', description: 'Dockerfile生成', category: 'Code' },
  { path: '/editorconfig-generator', icon: '⚙', displayName: 'EditorConfig Generator', description: '.editorconfig生成', category: 'Code' },
  { path: '/env-file-editor', icon: '⚙', displayName: '.env File Editor', description: '.envファイル編集', category: 'Code' },
  { path: '/er-diagram', icon: '🗂', displayName: 'ER Diagram', description: 'ER図作成', category: 'Code' },
  { path: '/git-commit-message', icon: '📝', displayName: 'Git Commit Message', description: 'Gitコミットメッセージ作成', category: 'Code' },
  { path: '/gitignore-generator', icon: '🚫', displayName: '.gitignore Generator', description: '.gitignore生成', category: 'Code' },
  { path: '/htaccess-generator', icon: '⚙', displayName: '.htaccess Generator', description: '.htaccess生成', category: 'Code' },
  { path: '/k8s-yaml-generator', icon: '☸', displayName: 'K8s YAML Generator', description: 'Kubernetes YAML生成', category: 'Code' },
  { path: '/license-chooser', icon: '📜', displayName: 'License Chooser', description: 'ライセンス選択支援', category: 'Code' },
  { path: '/markdown-to-slides', icon: '📊', displayName: 'Markdown to Slides', description: 'Markdownをスライドに変換', category: 'Code' },
  { path: '/mermaid-preview', icon: '📊', displayName: 'Mermaid Preview', description: 'Mermaidダイアグラムプレビュー', category: 'Code' },
  { path: '/nginx-config-generator', icon: '⚙', displayName: 'Nginx Config Generator', description: 'Nginx設定ファイル生成', category: 'Code' },
  { path: '/npm-package-info', icon: '📦', displayName: 'npm Package Info', description: 'npmパッケージ情報を取得', category: 'Code' },
  { path: '/package-json-validator', icon: '✅', displayName: 'package.json Validator', description: 'package.json検証', category: 'Code' },
  { path: '/plantuml-preview', icon: '📊', displayName: 'PlantUML Preview', description: 'PlantUMLプレビュー', category: 'Code' },
  { path: '/regex-builder', icon: '🔎', displayName: 'Regex Builder', description: '正規表現ビルダー', category: 'Code' },
  { path: '/robots-txt-generator', icon: '🤖', displayName: 'robots.txt Generator', description: 'robots.txt生成', category: 'Code' },
  { path: '/semver-calculator', icon: '🔢', displayName: 'SemVer Calculator', description: 'セマンティックバージョン計算', category: 'Code' },
  { path: '/sql-playground', icon: '🗃', displayName: 'SQL Playground', description: 'SQLプレイグラウンド', category: 'Code' },
  { path: '/systemd-unit-generator', icon: '⚙', displayName: 'Systemd Unit Generator', description: 'systemdユニットファイル生成', category: 'Code' },
  { path: '/tailwind-to-css', icon: '🎨', displayName: 'Tailwind to CSS', description: 'TailwindクラスをCSSに変換', category: 'Code' },
  { path: '/terraform-fmt', icon: '⚙', displayName: 'Terraform Formatter', description: 'Terraform設定ファイル整形', category: 'Code' },
  { path: '/tsconfig-builder', icon: '📘', displayName: 'tsconfig.json Builder', description: 'tsconfig.json設定ビルダー', category: 'Code' },

  // Color / CSS
  { path: '/color-converter', icon: '🎨', displayName: 'Color Converter', description: 'カラーコード変換', category: 'Color / CSS' },
  { path: '/color-picker', icon: '🖌', displayName: 'Color Picker', description: 'カラーピッカー', category: 'Color / CSS' },
  { path: '/color-mixer', icon: '🎨', displayName: 'Color Mixer', description: 'カラーミキサー', category: 'Color / CSS' },
  { path: '/color-shade', icon: '🌗', displayName: 'Color Shade', description: 'シェード・ティント生成', category: 'Color / CSS' },
  { path: '/color-brightness', icon: '☀', displayName: 'Color Brightness', description: '明度・彩度調整', category: 'Color / CSS' },
  { path: '/color-invert', icon: '🔄', displayName: 'Color Invert', description: '色反転', category: 'Color / CSS' },
  { path: '/color-blind-simulator', icon: '👁', displayName: 'Color Blind Sim', description: '色覚シミュレーション', category: 'Color / CSS' },
  { path: '/css-gradient', icon: '🌈', displayName: 'CSS Gradient', description: 'グラデーション生成', category: 'Color / CSS' },
  { path: '/css-box-shadow', icon: '🔲', displayName: 'CSS Box Shadow', description: 'Box Shadow生成', category: 'Color / CSS' },
  { path: '/css-border-radius', icon: '⬜', displayName: 'CSS Border Radius', description: 'Border Radius生成', category: 'Color / CSS' },
  { path: '/css-glassmorphism', icon: '🪟', displayName: 'Glassmorphism', description: 'Glassmorphism生成', category: 'Color / CSS' },
  { path: '/css-clip-path', icon: '✂', displayName: 'CSS Clip Path', description: 'Clip Path生成', category: 'Color / CSS' },
  { path: '/css-flexbox', icon: '📐', displayName: 'Flexbox Playground', description: 'Flexboxプレイグラウンド', category: 'Color / CSS' },
  { path: '/css-grid', icon: '🔳', displayName: 'CSS Grid', description: 'CSS Gridプレイグラウンド', category: 'Color / CSS' },
  { path: '/css-checkbox', icon: '☑', displayName: 'CSS Checkbox', description: 'Checkbox/Switch生成', category: 'Color / CSS' },
  { path: '/css-loader', icon: '⏳', displayName: 'CSS Loader', description: 'ローディングアニメーション', category: 'Color / CSS' },
  { path: '/color-palette-generator', icon: '🎨', displayName: 'Color Palette Generator', description: 'カラーパレット生成', category: 'Color / CSS' },
  { path: '/contrast-checker', icon: '👁', displayName: 'Contrast Checker', description: 'コントラスト比チェック', category: 'Color / CSS' },
  { path: '/css-animation-builder', icon: '✨', displayName: 'CSS Animation Builder', description: 'CSSアニメーション生成', category: 'Color / CSS' },
  { path: '/css-filter-generator', icon: '🎨', displayName: 'CSS Filter Generator', description: 'CSSフィルター生成', category: 'Color / CSS' },
  { path: '/css-text-shadow', icon: '✏', displayName: 'CSS Text Shadow', description: 'テキストシャドウ生成', category: 'Color / CSS' },
  { path: '/css-to-tailwind', icon: '🎨', displayName: 'CSS to Tailwind', description: 'CSSをTailwindクラスに変換', category: 'Color / CSS' },
  { path: '/font-preview', icon: '🔤', displayName: 'Font Preview', description: 'フォントプレビュー', category: 'Color / CSS' },
  { path: '/font-size-calculator', icon: '📐', displayName: 'Font Size Calculator', description: 'フォントサイズ計算', category: 'Color / CSS' },
  { path: '/gradient-mesh', icon: '🌈', displayName: 'Gradient Mesh Generator', description: 'グラデーションメッシュ生成', category: 'Color / CSS' },
  { path: '/icon-search', icon: '🔍', displayName: 'Icon Search', description: 'アイコン検索', category: 'Color / CSS' },
  { path: '/mockup-device', icon: '📱', displayName: 'Mockup Device', description: 'デバイスモックアップ', category: 'Color / CSS' },
  { path: '/noise-texture', icon: '🔲', displayName: 'Noise Texture Generator', description: 'ノイズテクスチャ生成', category: 'Color / CSS' },
  { path: '/pattern-generator', icon: '🔲', displayName: 'Pattern Generator', description: 'パターン生成', category: 'Color / CSS' },
  { path: '/responsive-preview', icon: '📱', displayName: 'Responsive Preview', description: 'レスポンシブプレビュー', category: 'Color / CSS' },
  { path: '/social-card-generator', icon: '🖼', displayName: 'Social Card Generator', description: 'OGP/ソーシャルカード生成', category: 'Color / CSS' },
  { path: '/svg-optimizer', icon: '✂', displayName: 'SVG Optimizer', description: 'SVG最適化', category: 'Color / CSS' },
  { path: '/svg-to-component', icon: '⚛', displayName: 'SVG to Component', description: 'SVG→Reactコンポーネント変換', category: 'Color / CSS' },

  // Image
  { path: '/image-crop', icon: '✂', displayName: 'Image Crop', description: '画像トリミング', category: 'Image' },
  { path: '/image-resize', icon: '📐', displayName: 'Image Resize', description: '画像リサイズ', category: 'Image' },
  { path: '/image-generate', icon: '🎨', displayName: 'Image Generator', description: 'ダミー画像生成', category: 'Image' },
  { path: '/image-grayscale', icon: '⚫', displayName: 'Image Grayscale', description: 'グレースケール変換', category: 'Image' },
  { path: '/image-transparent', icon: '🔍', displayName: 'Image Transparent', description: '画像透過処理', category: 'Image' },
  { path: '/image-trim', icon: '✂', displayName: 'Image Trim', description: '透過余白トリミング', category: 'Image' },
  { path: '/image-assets', icon: '🖼', displayName: 'Image Assets', description: '一括リサイズ', category: 'Image' },
  { path: '/image-compress', icon: '📦', displayName: 'Image Compress', description: '画像圧縮', category: 'Image' },
  { path: '/image-convert', icon: '🔄', displayName: 'Image Convert', description: 'フォーマット変換', category: 'Image' },
  { path: '/image-flip', icon: '🔃', displayName: 'Image Flip', description: '画像反転', category: 'Image' },
  { path: '/image-brightness', icon: '☀', displayName: 'Image Brightness', description: '明度調整', category: 'Image' },
  { path: '/image-filter', icon: '🎭', displayName: 'Image Filter', description: 'フィルター効果', category: 'Image' },
  { path: '/image-color-extract', icon: '🎨', displayName: 'Color Extract', description: '画像色抽出', category: 'Image' },
  { path: '/image-ascii-art', icon: '🔤', displayName: 'ASCII Art', description: 'アスキーアート変換', category: 'Image' },
  { path: '/image-favicon', icon: '⭐', displayName: 'Favicon Generator', description: 'ファビコン生成', category: 'Image' },
  { path: '/image-app-icon', icon: '📱', displayName: 'App Icon', description: 'アプリアイコン生成', category: 'Image' },
  { path: '/image-svg-blob', icon: '💧', displayName: 'SVG Blob', description: 'SVG Blob生成', category: 'Image' },
  { path: '/image-svg-pattern', icon: '🔲', displayName: 'SVG Pattern', description: 'SVGパターン生成', category: 'Image' },
  { path: '/image-svg-placeholder', icon: '🖼', displayName: 'SVG Placeholder', description: 'プレースホルダー生成', category: 'Image' },
  { path: '/image-to-base64', icon: '🔤', displayName: 'Image to Base64', description: 'Base64エンコード', category: 'Image' },
  { path: '/image-ocr', icon: '📖', displayName: 'OCR', description: '画像テキスト抽出', category: 'Image' },
  { path: '/handwriting-converter', icon: '✍', displayName: 'Handwriting', description: '手書き風変換', category: 'Image' },
  { path: '/ascii-chart', icon: '📊', displayName: 'ASCII Chart', description: 'ASCIIチャート生成', category: 'Image' },
  { path: '/ascii-table-generator', icon: '📋', displayName: 'ASCII Table Generator', description: 'ASCIIテーブル生成', category: 'Image' },
  { path: '/avatar-generator', icon: '👤', displayName: 'Avatar Generator', description: 'アバター画像生成', category: 'Image' },
  { path: '/business-card', icon: '💼', displayName: 'Business Card Designer', description: '名刺デザイン', category: 'Image' },
  { path: '/certificate-generator', icon: '🏆', displayName: 'Certificate Generator', description: '賞状・証明書生成', category: 'Image' },
  { path: '/chart-builder', icon: '📊', displayName: 'Chart Builder', description: 'インタラクティブチャート作成', category: 'Image' },
  { path: '/exif-editor', icon: '📷', displayName: 'EXIF Editor', description: '画像EXIFデータ編集', category: 'Image' },
  { path: '/graph-plotter', icon: '📊', displayName: 'Graph Plotter', description: 'グラフプロッター', category: 'Image' },
  { path: '/image-placeholder', icon: '🖼', displayName: 'Image Placeholder', description: 'プレースホルダー画像生成', category: 'Image' },
  { path: '/invoice-generator', icon: '🧾', displayName: 'Invoice Generator', description: '請求書生成', category: 'Image' },
  { path: '/pixel-art-editor', icon: '🎨', displayName: 'Pixel Art Editor', description: 'ドット絵エディタ', category: 'Image' },

  // PDF
  { path: '/pdf-merge', icon: '📑', displayName: 'PDF Merge', description: 'PDF結合', category: 'PDF' },
  { path: '/pdf-split', icon: '✂', displayName: 'PDF Split', description: 'PDF分割', category: 'PDF' },
  { path: '/pdf-compress', icon: '📦', displayName: 'PDF Compress', description: 'PDF圧縮', category: 'PDF' },
  { path: '/pdf-rotate', icon: '🔄', displayName: 'PDF Rotate', description: 'ページ回転', category: 'PDF' },
  { path: '/pdf-metadata', icon: 'ℹ', displayName: 'PDF Metadata', description: 'メタデータ編集', category: 'PDF' },
  { path: '/pdf-watermark', icon: '💧', displayName: 'PDF Watermark', description: 'ウォーターマーク', category: 'PDF' },
  { path: '/pdf-password', icon: '🔒', displayName: 'PDF Password', description: 'パスワード保護', category: 'PDF' },
  { path: '/pdf-to-image', icon: '🖼', displayName: 'PDF to Image', description: 'PDF→画像変換', category: 'PDF' },
  { path: '/image-to-pdf', icon: '📄', displayName: 'Image to PDF', description: '画像→PDF変換', category: 'PDF' },

  // Video
  { path: '/video-to-gif', icon: '🎬', displayName: 'Video to GIF', description: '動画→GIF変換', category: 'Video' },
  { path: '/gif-frame-extractor', icon: '🖼', displayName: 'GIF Frame Extractor', description: 'GIFフレーム抽出', category: 'Video' },
  { path: '/screen-recorder', icon: '🎥', displayName: 'Screen Recorder', description: '画面録画', category: 'Video' },
  { path: '/webcam-test', icon: '📷', displayName: 'Webcam Test', description: 'カメラテスト', category: 'Video' },
  { path: '/video-compress', icon: '📦', displayName: 'Video Compress', description: '動画圧縮', category: 'Video' },
  { path: '/video-mute', icon: '🔇', displayName: 'Video Mute', description: '動画音声削除', category: 'Video' },
  { path: '/video-rotate', icon: '🔄', displayName: 'Video Rotate', description: '動画回転', category: 'Video' },
  { path: '/video-speed', icon: '⏩', displayName: 'Video Speed', description: '動画速度変更', category: 'Video' },
  { path: '/video-thumbnail', icon: '🖼', displayName: 'Video Thumbnail', description: 'サムネイル抽出', category: 'Video' },
  { path: '/video-trim', icon: '✂', displayName: 'Video Trim', description: '動画トリミング', category: 'Video' },
  { path: '/video-watermark', icon: '💧', displayName: 'Video Watermark', description: '動画ウォーターマーク', category: 'Video' },
  { path: '/audio-convert', icon: '🎵', displayName: 'Audio Convert', description: 'オーディオ形式変換', category: 'Video' },
  { path: '/audio-merge', icon: '🎵', displayName: 'Audio Merge', description: 'オーディオ結合', category: 'Video' },
  { path: '/audio-metronome', icon: '🎵', displayName: 'Audio Metronome', description: 'メトロノーム', category: 'Video' },
  { path: '/audio-noise-gate', icon: '🎵', displayName: 'Audio Noise Gate', description: 'ノイズゲート', category: 'Video' },
  { path: '/audio-speed', icon: '🎵', displayName: 'Audio Speed Changer', description: 'オーディオ速度変更', category: 'Video' },
  { path: '/audio-tone-generator', icon: '🎵', displayName: 'Audio Tone Generator', description: 'トーン生成', category: 'Video' },
  { path: '/audio-trim', icon: '🎵', displayName: 'Audio Trim', description: 'オーディオトリミング', category: 'Video' },
  { path: '/audio-visualizer', icon: '🎵', displayName: 'Audio Visualizer', description: '音声波形可視化', category: 'Video' },

  // Generator
  { path: '/password-generator', icon: '🔑', displayName: 'Password Generator', description: 'パスワード生成', category: 'Generator' },
  { path: '/uuid-generator', icon: '🆔', displayName: 'UUID/ULID Generator', description: 'UUID/ULID生成', category: 'Generator' },
  { path: '/dummy-data-generator', icon: '📋', displayName: 'Dummy Data Generator', description: 'ダミーデータ生成', category: 'Generator' },
  { path: '/htpasswd-generator', icon: '🔐', displayName: '.htpasswd Generator', description: '.htpasswd生成', category: 'Generator' },
  { path: '/bip39-generator', icon: '🌱', displayName: 'BIP39 Generator', description: 'ニーモニック生成', category: 'Generator' },
  { path: '/qr-code-generator', icon: '📱', displayName: 'QR Code Generator', description: 'QRコード生成', category: 'Generator' },
  { path: '/qr-code-reader', icon: '📷', displayName: 'QR Code Reader', description: 'QRコード読取', category: 'Generator' },
  { path: '/barcode-generator', icon: '📊', displayName: 'Barcode Generator', description: 'バーコード生成', category: 'Generator' },
  { path: '/seo-ogp-generator', icon: '🏷', displayName: 'OGP Generator', description: 'OGPメタタグ生成', category: 'Generator' },
  { path: '/morpheme-analyzer', icon: '🔬', displayName: 'Morpheme Analyzer', description: '文字種別分割', category: 'Generator' },
  { path: '/braille-converter', icon: '⠃', displayName: 'Braille Converter', description: '点字変換', category: 'Generator' },
  { path: '/bookmark-manager', icon: '🔖', displayName: 'Bookmark Manager', description: 'ブックマーク管理', category: 'Generator' },
  { path: '/decision-wheel', icon: '🎡', displayName: 'Decision Wheel', description: '意思決定ホイール', category: 'Generator' },
  { path: '/file-rename-batch', icon: '📁', displayName: 'File Rename Batch', description: 'ファイル一括リネーム', category: 'Generator' },
  { path: '/flashcard', icon: '📝', displayName: 'Flashcard', description: 'フラッシュカード', category: 'Generator' },
  { path: '/gantt-chart', icon: '📊', displayName: 'Gantt Chart', description: 'ガントチャート', category: 'Generator' },
  { path: '/habit-tracker', icon: '✅', displayName: 'Habit Tracker', description: '習慣トラッカー', category: 'Generator' },
  { path: '/kanban-board', icon: '📋', displayName: 'Kanban Board', description: 'カンバンボード', category: 'Generator' },
  { path: '/kaomoji-picker', icon: '(^_^)', displayName: 'Kaomoji Picker', description: '顔文字ピッカー', category: 'Generator' },
  { path: '/note-pad', icon: '📝', displayName: 'Note Pad', description: 'メモ帳', category: 'Generator' },
  { path: '/pivot-table', icon: '📊', displayName: 'Pivot Table', description: 'ピボットテーブル', category: 'Generator' },
  { path: '/treemap-generator', icon: '📊', displayName: 'Treemap Generator', description: 'ツリーマップ生成', category: 'Generator' },
  { path: '/typing-speed-test', icon: '⌨', displayName: 'Typing Speed Test', description: 'タイピング速度テスト', category: 'Generator' },
  { path: '/whiteboard', icon: '🖊', displayName: 'Whiteboard', description: 'ホワイトボード', category: 'Generator' },
  { path: '/zalgo-text', icon: '🔮', displayName: 'Zalgo Text Generator', description: 'ザルゴテキスト生成', category: 'Generator' },
  { path: '/zip-creator', icon: '🗜', displayName: 'ZIP Creator', description: 'ZIPファイル作成', category: 'Generator' },
  { path: '/zip-extractor', icon: '📂', displayName: 'ZIP Extractor', description: 'ZIPファイル展開', category: 'Generator' },

  // Network
  { path: '/cidr-calculator', icon: '🌐', displayName: 'CIDR Calculator', description: 'CIDR計算', category: 'Network' },
  { path: '/subnet-calculator', icon: '🌐', displayName: 'Subnet Calculator', description: 'サブネット計算', category: 'Network' },
  { path: '/user-agent-parser', icon: '🔎', displayName: 'User Agent Parser', description: 'UA解析', category: 'Network' },
  { path: '/display-checker', icon: '🖥', displayName: 'Display Checker', description: '画面情報チェック', category: 'Network' },
  { path: '/validator-html', icon: '✅', displayName: 'HTML Validator', description: 'HTML検証', category: 'Network' },
  { path: '/validator-xml', icon: '✅', displayName: 'XML Validator', description: 'XML検証', category: 'Network' },
  { path: '/validator-password', icon: '🔒', displayName: 'Password Checker', description: 'パスワード強度チェック', category: 'Network' },
  { path: '/csv-to-chart', icon: '📈', displayName: 'CSV to Chart', description: 'CSV→グラフ', category: 'Network' },
  { path: '/csv-to-sql', icon: '🗃', displayName: 'CSV to SQL', description: 'CSV→SQL変換', category: 'Network' },
  { path: '/list-compare', icon: '📋', displayName: 'List Compare', description: 'リスト比較', category: 'Network' },
  { path: '/list-randomize', icon: '🔀', displayName: 'List Randomizer', description: 'リストランダム化', category: 'Network' },
  { path: '/coordinate-converter', icon: '🗺', displayName: 'Coordinate Converter', description: '座標変換', category: 'Network' },
  { path: '/cors-checker', icon: '🌐', displayName: 'CORS Checker', description: 'CORSヘッダーチェック', category: 'Network' },
  { path: '/csp-builder', icon: '🛡', displayName: 'CSP Builder', description: 'Content Security Policy生成', category: 'Network' },
  { path: '/dns-lookup', icon: '🌐', displayName: 'DNS Lookup', description: 'DNS情報取得', category: 'Network' },
  { path: '/geo-distance', icon: '🗺', displayName: 'Geo Distance Calculator', description: '地点間距離計算', category: 'Network' },
  { path: '/geojson-viewer', icon: '🗺', displayName: 'GeoJSON Viewer', description: 'GeoJSONビューア', category: 'Network' },
  { path: '/http-header-viewer', icon: '🌐', displayName: 'HTTP Header Viewer', description: 'HTTPヘッダー表示', category: 'Network' },
  { path: '/http-request-builder', icon: '🌐', displayName: 'HTTP Request Builder', description: 'HTTPリクエストビルダー', category: 'Network' },
  { path: '/ip-address-info', icon: '🌐', displayName: 'IP Address Info', description: 'IPアドレス情報', category: 'Network' },
  { path: '/network-port-reference', icon: '🔌', displayName: 'Network Port Reference', description: 'ネットワークポート一覧', category: 'Network' },
  { path: '/password-strength', icon: '🔒', displayName: 'Password Strength Checker', description: 'パスワード強度チェッカー', category: 'Network' },
  { path: '/url-parser', icon: '🔗', displayName: 'URL Parser', description: 'URLパース・解析', category: 'Network' },
  { path: '/websocket-tester', icon: '🔌', displayName: 'WebSocket Tester', description: 'WebSocketテスター', category: 'Network' },
  { path: '/what3words-converter', icon: '🗺', displayName: 'Grid Reference Converter', description: 'グリッド参照変換', category: 'Network' },
  { path: '/data-anonymizer', icon: '🔒', displayName: 'Data Anonymizer', description: 'データ匿名化', category: 'Network' },
  { path: '/data-masking', icon: '🔒', displayName: 'Data Masking', description: 'データマスキング', category: 'Network' },
  { path: '/data-sampler', icon: '📊', displayName: 'Data Sampler', description: 'データサンプリング', category: 'Network' },
  { path: '/file-metadata-viewer', icon: '📋', displayName: 'File Metadata Viewer', description: 'ファイルメタデータ表示', category: 'Network' },

];